### ISSUE TITLE
Suggestion for parser: shift operator

### ISSUE THREAD

**Issue by bgold-cosmos** [tidalcycles/Tidal#111]
One thing I've tried to implement but can't figure out how to properly do is to have a "shift" operator in Tidal's string EDSL.  Something like `"bd ~ bd< ~"` which would parse to `"bd [~ bd] ~ ~"`, for example (and `"bd bd> ~ ~"` would parse to the same).  Perhaps the default would be to shift half a "slot" and you could add a number for shifting smaller fractions, e.g. `"bd ~ bd<3 ~"` == `"bd [~ ~ bd] ~ ~"`.   This could save a lot of typing.

I tried to implement this a while back and got stuck on not being able to get the parser to "move" sub-patterns outside their "slot" in the larger pattern, but I'm happy to help code something up if anyone has ideas for how to get past that.

**Comment by lennart** [comment]
I think, this would need to look ahead within pPart and parse the next thing after the part itself (and after replication, that is "bd ! ! bd<" should produce "bd bd [bd bd] ~" no?)

the new parser would parse a combination of pPart followed by the shiftleft operator and then integrate it into the original part. since the thing followed by the leftshifted thing could also be left shifted, we could use pPart unmodified: bd ~ sn< cp< should parse to bd [~ [sn cp]] ~ shouldn't it?

not sure if this works in combination with the more straightforward solution for rightshifting (as this would not need to get out of its own slot)

I haven't tested this but this _might_ work. actually I might be trying this out soonish

…

**Comment by jwaldmann** [comment]
(this issue is under consideration for the HaL Hackathon)

Is this the "beat rotation" operator ( https://tidalcycles.org/functions.html#beat-rotation ), and this issue is about giving it a concrete representation in the String EDSL? 

Or is this a new operator? If yes, does it make sense "in the abstract" (outside the string EDSL)? If yes, what is its type, its semantics?

I guess it's something more complicated because you are already discussing how to parse it.

**Comment by bgold-cosmos** [comment]
Yes, the idea is that it has the same effect as the beat rotation operator.  But semantically it's not clear if it would/should work exactly the same - "operators" in the String EDSL typically operate on and within subpatterns, while pattern transforming functions act on an entire pattern.  
For example, these two are actually different things:
```
d1 $ s "bd cp/2"

d1 $ slow "1 2" $ s "bd cp"
```
So my recollection is that I was having trouble even defining the problem in a consistent way, let alone figuring out how to implement it in the parser.

**Comment by lennart** [comment]
Since it seems that both of the other issues elected for the hackathon 2017 in Leipzig concern the parser, it might be wise to schedule working on this issue __after__ the others or focus only on the conceptual side of it, that is:

_defining the problem in a consistent way_ (which would be the first step, as @bgold-cosmos pointed out)

Mainly because the participants should have already learned something about _how_ the tidal parser works, before stepping into modifying its _behaviour_ (the other tickets augment/extend it while keeping the same _logic_).

**Comment by lennart** [comment]
One note on the meaning of the new symbol `<` would be, that the default shift length should be `1` and not `1/2`.

So in order to shift only half a slot would be `<2` and a third `<3` and so on. Therefore the numbering would be without _gaps_.

**Comment by yaxu** [comment]
What cases would this be useful for?  The `<~` and `~>` operators are generally not used outside of higher order things like `every`

**Comment by bgold-cosmos** [comment]
It might be worth some rethinking now (it's been a while since the original issue).

But originally, I was trying to work out a way to quickly denote a shift of a single beat (or subpattern) within a cycle.  If I want to change from `[bd cp sn cp]` to `[bd cp [~ sn] cp]` it's a bit of extra typing and I tend to make mistakes if the pattern is longer and more complex.  I noticed I tend to use patterns like `x [~ x]` or `x [~ x ~ ~]` fairly often, so the savings (both in typing and reading comprehension) of having a shorthand `x x>2` or `x x>4` might add up.

Outside the DSL this has to be done as something like `inside 4 (every' 4 2 (0.5 ~>)) "[bd cp sn cp]"` which is horribly verbose, although I suppose it wouldn't be hard to write a shorthand version.

**Comment by yaxu** [comment]
I think I'd always want to type `x [~ x ~ ~]` to then have the possibility of adding `x [~ x x ~]`. So I wonder if this would be better as a keyboard macro in an editor

Although actually I'm not clear on what the `4` in `>4` means

**Comment by vivid-synth** [comment]
Wouldn't this introduce ambiguity? I.e.

```haskell
gain "1 3>3 2"
```

Which ```3``` is the value, and which is the shift amount?

I'm also in general a fan of keeping the string language simple and without too much "feature creep"

**Comment by vivid-synth** [comment]
Also, doesn't tidal have a ```"<foo bar>"``` syntax (i.e. enclosing ```foo``` and ```bar``` in ```<>```?)

**Comment by bgold-cosmos** [comment]
I think the left operand would always be the value, but the `"<x x>"` syntax is new since I opened the issue.

**Comment by yaxu** [comment]
I think I'm with @vivid-synth, I can imagine scenarios where this could be useful, but on the other hand I can only keep so much syntax in my head.. Shall we close this for now?

**Comment by pdcawley** [comment]
Per a discussion in Lurk, this would be useful for expressing flams or gracenotes, but with the added wrinkle that it would be more useful if there were a way to express something to be played on the beat rather than just a rest. Syntax along the lines of `a<<<g` perhaps?
