### ISSUE TITLE
insufficient randomness

### ISSUE THREAD

**Issue by zzkt** [tidalcycles/Tidal#134]
separate calls to `rand` (including `irand` and `randcat`) during the same event(?) will produce the same results. this could be considered a bug or feature, however producing different random numbers for each call in the same event could be more interesting musically.

```
tidal> rand
(0.5672781162870792 0 1)
tidal> rand
(0.5672781162870792 0 1)
```

**Comment by kindohm** [comment]
Personally, I would consider the "same-random-values" quirk a valuable feature that I would not like to lose.  I do stuff like this very often:

```
c1 $ stack [ degrade $ sound "bd*8", degrade $ sound "arpy*8" ]
```

Where the two patterns in the stack _both_ result in the same randomness. The `degrade` function randomly removes the same events from both patterns. I really like this. I personally get a *lot* of use out of this quirk/feature.

If I want to make sure the two patterns get different random degradations, then I use `shift` or `<~`:

```
c1 $ stack [ degrade $ sound "bd*8", degrade $ (1024 <~) $ sound "arpy*8" ]
```

Would it be OK to both preserve the existing behavior _and_ add this new behavior via a different feature (or rename the existing behavior into a new function name)? Is it even possible to add the new behavior? I recall many discussions where @yaxu said it was not possible.

**Comment by yaxu** [comment]
Yes the problem is that tidal holds no state, and RNGs are all about state. A tidal pattern is a pure function from time to events, which gives a lot of flexibility in terms of the manipulation of time, but makes anything dependent on previous events, like a 'random' number stream, impossible. 

I am thinking about how to introduce state to Tidal, but if there was an impure RNG that held its own state, then things like `palindrome rand` would stop working.

The time shifting thing works, I think you could shift by a tiny amount `0.0000001 <~` to get a completely different stream, or make a function like `let randomer n = (toRational (n * 0.0000001)) <~ rand` to make indexing these easier, e.g. `d1 $ sound "bd" # speed (randomer 1) # pan (randomer 2)`.

It might be good to duplicate this discussion on ask.tidalcycles.org.

**Comment by zzkt** [comment]
see also http://ask.tidalcycles.org/question/195/randomness/
