### ISSUE TITLE
semantics of unit for synths

### ISSUE THREAD

**Issue by telephon** [tidalcycles/Tidal#205]
I am not sure how we should best interpret the `unit` parameter in SuperDirt when the instrument is a synth. What would be the expected (or most interesting) behaviour?

Note that (in 1.0-dev), by default, the `unitDuration` equals `delta` (time between events). If you provide a `unitDuration` for your synth, it will behave more like a sample (e.g. normally, its sustain will  be independent of speed, e.g.).

One way to do it would be to ignore `unit` unless `unitDuration` were explicitly given. But maybe there are better ways.

**Comment by bgold-cosmos** [comment]
I think there's an underlying question of what `speed` should mean for synths.  Currently it doesn't really do anything other than alter the duration calculation, which I'm starting to think isn't ideal.

The intent of `unit` for samples was basically to make it easer to stretch samples to some number/fraction of a cycle (e.g. for beatmatching), or to play a sample for a specific amount of time in seconds. Neither of these were really possible with `begin` & `end` without knowing the original sample duration.

For synths, the first case is probably handled just as well with `legato` since SuperDirt knows `delta`, and the second case is what `sustain` does.  So I would suggest `unit` doesn't really serve a purpose for synths and could be ignored.  I think I'd even suggest the same for `speed`.

**Comment by telephon** [comment]
Sounds very reasonable. One case might be when you want to write a *special* synth that closely simulates sample behavior, or that is a weird metaphor of it. When you mix synths and samples in a tidal pattern you then would get interesting shifts.

I believe this is best served by setting `unitDuration` explicitly in the [`DirtSoundLibrary`](https://github.com/musikinformatik/SuperDirt/blob/1.0-dev/classes/DirtSoundLibrary.sc#L50.

The `speed` parameter is accessible from any synth and can be used by it. So it is more an issue of using it in more default synths, perhaps? Of course, we could also make it map to `freq` as a standard thing. Would you prefer that?

**Comment by annybs** [comment]
I'm going to start putting my feedback on the delta vs. sustain issue here, rather than putting it in the Slack channel where it'll disappear in time. Here's my basic problem, using the simplest possible code:

```supercollider
(
SynthDef(\atest, { |delta=1, sustain=1|
	[delta, sustain].poll;
}).add;
)
```

```haskell
cps 1

d1 $ slow 2 $ sound "atest ~" # octave 3
{- yields:
UGen Array [0]: 1
UGen Array [1]: 0.999
-}

d1 $ slow 2 $ chop 4 $ sound "atest ~" # octave 3
{- yields:
UGen Array [0]: 0.25
UGen Array [1]: 0.0605
-}
```

In the `chop` example there, `delta` (value 0) is correct, but `sustain` (v. 1) is obviously incorrect. The 'actual' synth I'm working on shapes its output with an envelope scaled to the original event and slices like a sample - i.e. at 60BPM, the sound should be 1s and chopped into parts of 0.25s each.

At the moment, because `sustain` values are incorrect, I'm recalculating the original event length with:

`var rsustain = delta / absdif(begin, end);`

Which is fine for now, it just feels a bit weird using `delta` instead of `sustain`.

Sustain is wrong by seemingly by a factor equivalent to the number of parts resulting from chop. In this case, I'm chopping 4, and `0.25/4 = 0.0625` so I guess we get 0.0605 from SuperDirt subtracting a few milliseconds for fade-in and -out.

I find this whole thing fairly confusing TBH, I think what throws me is simply that sustain is wrong, unless it's _supposed_ to be divided like this - if so, I'd like to understand the reasoning behind that :)

**Comment by bgold-cosmos** [comment]
I think what's happening is that Tidal and SuperDirt and doing some of the same work when `chop` is involved. For example:

`chop 4 $ sound "foo"`
turns into
`sound "foo*4" # begin "0 0.25 0.5 0.75" # end "0.25 0.5 0.75 1.0"`

This happens before anything leaves Tidal!  Then SuperDirt gets these messages, and since it also knows about `delta` it sees four sounds, each with `delta` of 0.25, but also each one has a length that's been altered with `begin` and `end`.  If the instrument were a sample it would normally ignore `delta` unless `legato` is specified, and everything sounds fine.  But if it's a synth, it calculates `sustain` by multiplying `delta` by `end - begin`.  This is the behavior you're seeing.

I think synths being aware of `delta` is kind of nice, so IMO the thing to do might be to just have synths not use `begin` and `end` when calculating `sustain`.  That should avoid this issue you're seeing.

**Comment by telephon** [comment]
Yes, the now (in the latest version), `begin` and `end` don't change sustain, unless you explicitly fix the synth duration with `unitDuration` (which then ignores `delta`).

**Comment by yaxu** [comment]
@telephon is this still an issue?

**Comment by telephon** [comment]
I don't think so. Reopen if needed!
