### ISSUE TITLE
ASTs everywhere?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#217]
@vivid-synth I'm just pondering how the ASTs that the sequence parser generates could make visualising the parse tree quite straightforward. Would it make sense to make the whole of tidal work this way? i.e. `slow` would simply be an alias for `TPat_Slow`, and `d1` or whatever would turn this into a function as an additional step before passing the pattern to the scheduler. I'm not sure how fiddly/useful this extra step of indirection would be in practice though..

**Comment by vivid-synth** [comment]
This would definitely make tracking down issues like https://github.com/tidalcycles/Tidal/issues/211 and https://github.com/tidalcycles/Tidal/issues/185 easier, since you can just inspect the outputs. It'd also make writing tests easier, since you could write tests of the form:

```haskell
(rev $ slow 4 $ sound "bd sn")
   == error "some value here"
```

Which you can't do at the moment because there's no equality test for functions.

**Comment by vivid-synth** [comment]
This would also allow for non-realtime rendering -- e.g. you write a tidal "score" and render it as a ```.wav``` or ```.flac``` instantaneously.

**Comment by jwaldmann** [comment]
(from discussion at hackathon)

while we're at it - the AST should more closely represent (abstract) syntax. At the moment, the parser includes too much semantics. For instance, currently

```
parseRhythm  pVocable "x@2 y"
TPat_Cat [TPat_Cat [TPat_Zoom (0 % 1,1 % 2) (TPat_Atom "x"),TPat_Zoom (1 % 2,1 % 1) (TPat_Atom "x"),TPat_Atom "y"]]
```
(it compute the semantics of "@") while I would  expect something like
```
... TPat_At (TPat_Atom "x") (TPat_Atom "2") ...
```
and the semantics would be determined elsewhere.

**Comment by yaxu** [comment]
I'm going to take a run at this. Experiments with #530 show it would make some interesting things possible.

From what @jwaldmann says above, it seems the AST should simply reflect the functions? In which case building the AST datatype is just a case of taking the type signatures of all the Tidal functions that are used (from e.g. the ghci `:browse` command) and transforming them with a bit of regex..

Then making AST analogues of all the functions by adding them to the list here:
  https://github.com/tidalcycles/Tidal/blob/topic-ast/src/Sound/Tidal/AST.hs

Any comments from people more experienced with ASTs?

**Comment by yaxu** [comment]
I did make something like this for my old `texture` project:
  https://github.com/yaxu/hstexture/blob/master/Texture/Types.hs

It involved replicating some of the Haskell type system to support polymorphism and so on. This gets complicated!

**Comment by jwaldmann** [comment]
Hi. I'll just repeat what I said above: the parser should know just function/operator symbols (and predecence of operators), and nothing about semantics. The goal usually is that it should be possible to (pretty) print the AST, and get back the exact input string.

I think this is also easiest to implement, as it treats all functions/operator symbols equally.
If some syntax gets translated away by the parser, and some does not, then this leads to discussions about which is which, and also it is impossible to pretty-print the original form.

Instead of "minimal AST" I'd consider  "minimal API" (containing the core functions -
that need to know about the implementation of `Pattern`) and "convenience API" (containing functions that can treat the `Pattern` type as abstract, and are implemented by calling core functions). But I think Tidal already has that distinction.

In Haskell land, similar AST-only packages are https://hackage.haskell.org/package/language-c https://hackage.haskell.org/package/language-java https://hackage.haskell.org/package/haskell-src-exts 
All of them just provide parser and printer. E.g., "Manipulating Java source: abstract syntax, lexer, parser, and pretty-printer."

**Comment by jwaldmann** [comment]
> replicating some of the Haskell type system

But that's semantics - what's that to do in a parser? Is this about how to show errors to the user? There's two ways:

1. the parser checks syntax and alse checks types (then a type error appears as a parse error)
2. the parser produces the AST, then the AST gets type-checked. 

I recommend the second. Then the problem appears that the error message should contain snippets of the original source code. This can be solved with an AST that is exact-printable (see previous message), or with an AST that has source annotations (file name, line/column number) for each node.

But Tidal is silent about such errors at the moment anyway?

There are typed ASTs and other extensions (cf. http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.63.6896 ) but that's too much for our use case - e.g., we don't have names and scopes (in the Tidal sub-language that gets parsed from strings - of course we have them in the outer language (Haskell) but that is handled by ghci)

**Comment by lnfiniteMonkeys** [comment]
Not sure if this is exactly the same thing, but I'll throw it in anyway in hope it's useful.

I'm experimenting with something similar in TimeLines, namely having function names be placeholders for the functions they represent and not the functions themselves, so that when they're chained they don't just evaluate and return the result, but rather an AST that can be stored, traversed, simplified, evaluated etc. I think the term for this is CAS, Computer Algebra System.

As an example, in `foo = add 1 $ sin $ 2*pi*t`, `foo` would be of type `SigExpr` and its value would be equal/translated to:
`BinExpr Add (ConstExpr 1) $ UnExpr Sin $ BinExpr Mult (ConstExpr 2) $ BinExpr Mult (ConstExpr Pi) (IdExpr)`

As a last step, this expression would be passed to a `SigExpr a -> Signal a` function, which recursively simplifies the tree (replacing things like `BinExpr Mult 0 foobar` with `ConstExpr 0` etc.) before turning each Expr into its corresponding function. 

This, however, requires that the UI functions use the expression wrapper type in their signatures, so for example `degradeBy :: Pattern Double -> Pattern a -> Pattern a` would become `PattExpr Double -> PattExpr a -> PattExpr a`, unless the Expr behaviour gets embedded in the Pattern datatype itself.

The relevant code for this so far is here:
[https://github.com/lnfiniteMonkeys/TimeLines/blob/wip/Sound/TimeLines/Expression.hs](https://github.com/lnfiniteMonkeys/TimeLines/blob/wip/Sound/TimeLines/Expression.hs)

**Comment by yaxu** [comment]
Thanks @lnfiniteMonkeys, that's helpful.

I'm trying to get my head around how to cope with things like partial application and polymorphism with such an approach. Am I right that these aren't implemented/needed in timelines?

**Comment by lnfiniteMonkeys** [comment]
Polymorphism is indeed not necessary or used much at the moment, but the `Signal` datatype itself is polymorphic and, where not overly complicated, so are the functions working with it. 

(`Signal` is essentially what `Pattern` was in the pre-1.0 version of Tidal, but instead of being a function of `(Time, Time) -> [a]` it's a `Time -> a` that gets mapped over a list of sampling times, so that it's independent of sampling rates)

The `SigExpr` type is polymorphic too, so as long as the types of all expressions match along the way then it should be able to do things like `fromList ["foo", "bar", "foobar"] $ sin t`, which would be represented as something like `BinExpr FromList (ConstList ["foo", "bar", "foobar"]) $ UnExpr Sin IdExpr` and have type `SigExpr String`.

As for partial application, the Expr types use Haskell's vanilla type constructors which I believe do currying just like any Haskell function. For example, one of the constructors for `SigExpr` is `BinExpr BinOp SigExpr SigExpr`, which expects three arguments but can be curried to expect one or both of the expressions to apply the binary operator on. Something like `(slow 2) :: SigExpr a -> SigExpr a` would be equal to `(BinExpr Slow (ConstExpr 2)) :: SigExpr a -> SigExpr a`. 

Is this what you are talking about?

**Comment by yaxu** [comment]
Ok thanks, so partial application doesn't seem to be a problem. By polymorphism I meant polymorphic functions - type variables with constraints. I think I just need to sit down and experiment with it really!

**Comment by yaxu** [comment]
I guess the problem with relying upon partial application of constructors is that they are opaque. So if I had this minimal tidal representation:

```
data P a = P_Atom a
         | P_Fast (P Time) (P a)
         | P_Slow (P Time) (P a)
         | P_Every (P Int) (P a -> P a) (P a)

instance (Show a) => Show (P a) where
  show (P_Atom a) = show a
  show (P_Fast t p) = "fast " ++ show t ++ " " ++ show p
  show (P_Slow t p) = "slow " ++ show t ++ " " ++ show p
  show (P_Every n f p) = "every " ++ show n ++ " (function) " ++ show p
```

`P_Every (P_Atom 3) (P_Fast (P_Atom 2)) (P_Atom "a")` would give `every 3 (function) "a"`

and I can't see how to send up with `every 3 (fast 2) "a"`

**Comment by lnfiniteMonkeys** [comment]
Re: constrained polymorphism, if I understand it correctly it should be as simple as 
``` haskell
fast :: (Num a) => Expr a -> Expr b -> Expr b
```
The way I understand it, an `Expr` type can be used in exactly the same ways and places that a `Pattern` would, as long as they have the same typeclass instances and at the very end you have a way of turning each `Expr` into its corresponding `Pattern`.

I see better what the problem is with partial application now, I don't think it's possible to have a `Show` instance for any `a -> b` function in Haskell. The issue here is that the second argument of `every` is not a pattern, but a function from one to another, and so an expression of that doesn't fit within the `P` datatype. Instead, I think an explicit type-level distinction between expressions of `Pattern a`s and `Pattern a -> Pattern a`s is a good first step.

Similarly, functions like `fast`, `slow` etc. can be separated in operator datatypes (similar to the `UnOp` and `BinOp` types in the file I linked above). 

Also, partial application can be made explicit by doing something like:
``` haskell
-- Pattern a -> Pattern a
data UnOp a = Decimate             
            | Mute
            | ...
            | PartiallyAppliedBin (BinOp a) (P a)

-- Pattern a -> Pattern a -> Pattern a
data BinOp a = Fast
             | Slow
             | DegradeBy
             | PartiallyAppliedTurn (TurnOp a) (P a) (P a)
             | ...
```

These operators can then get transformed to their respective functions using something like to this
``` haskell
toUnFunc :: UnOp -> ((Pattern a) -> (Pattern a))
toBinFunc :: BinOp -> ((Pattern a) -> (Pattern a) -> (Pattern a))
```

Then the type signature of `every` becomes
``` haskell
every :: (P Int) -> UnOp -> (P a) -> (P a)
```

I haven't had enough time to think this through, and my Haskell is a bit rusty so I'm sure there's some other issue with the above snippets, but I'm confident that we're on to something here.

**Comment by yaxu** [comment]
Interesting, but wouldn't that require a constructor for every combination of types present in Tidal, as well as the partially applied versions? Error messages are another concern..

**Comment by lnfiniteMonkeys** [comment]
>  wouldn't that require a constructor for every combination of types present in Tidal

I don't fully understand why that would be the case, but then again I don't fully understand Haskell's type system either. If you are referring to the `a` type variable being the same across signatures then I think you could do this instead
``` haskell
toBinFunc :: BinOp -> ((Pattern a) -> (Pattern b) -> (Pattern c))
```
although I don't know if this means that `a`, `b`, and `c` necessarily have to be different types or if there's also a way for them to be the same.

Perhaps another thought is implementing some of these ideas at the typeclass level, instead of bundling them in the same types, so different operators can have different type constraints/signatures but still share a similar interface.

Of course, it might well be that Tidal's case requires a much more sophisticated approach than what might work for TimeLines, but I still think that they're similar enough at their core for this to at least be a direction worth considering.

**Comment by yaxu** [comment]
Well there isn't a Tidal function with type signature `(Pattern a) -> (Pattern b) -> (Pattern c)`. 

`fast :: Pattern Time -> Pattern a -> Pattern a` does indeed match with `(Pattern a) -> (Pattern b) -> (Pattern c)`, but not vice versa.. So you'd end up allowing incompatible values being applied to functions, and type inference wouldn't be able to do its magic.

**Comment by dktr0** [comment]
I think it could help to be more clear about what kind of problem/desire is being addressed here.

My guess/read is that it is this: to have more of the notations that people use in/around Tidal represented in some kind of recursive, articulated data structure rather than simply as a function from time to values - so that information is available elsewhere about not only what the ultimate function from time to value is, but also about in what way the artist programmer is specifying that intention. So that, for example, visualization of program state can be directed back to a specific GUI object, etc etc etc.

If so, then I think @jwaldmann's comment about not having semantics is helpful. For the purpose of retaining the structure of the programmer's intention, the tree just needs to be able to reflect the compositional structure completely - it is okay if invalid programs can be constructed with the provided structure - checking that the tree is actually realizable, getting from it a rendering function from time to values, etc, would be separate steps. (It is totally possible to express invalid Haskell programs with the types from haskell-src-exts or Template Haskell.)

So that suggests something like this - no polymorphism - which (see comments further below) is basically the Exp type from haskell-src-exts:
data TidalExp = 
  ... constructors that represent what you can do inside "" notation (but no type arguments!)...
  App TidalExp TidalExp |
  InfixApp TidalExp TidalExp TidalExp |
  Operator String |
  Identifier String
  ..etc...

fast 2 "0 1" [...as an intention, is represented as...] (App (App (Identifier "fast) (Int 2)) (Quotes ...)) 

And if you want you can go down this road in order to retain compatibility with on-the-fly interpretation by GHCI (as it is currently done):
fast :: TidalExp -> TidalExp -> TidalExp
fast t p = App (App (Identifier "fast") t) p

In the example above TidalExp would be made an instance of relevant typeclasses to allow literals like 2 to be magicked into TidalExp.

I think it is important to note that outside of the " " Tidal currently has *no* syntax that is not that of Haskell. So the types of haskell-src-exts already provide for everything one can compose in Tidal, and then some. And MiniTidal has already provided a(n increasingly complete) model of going from haskell-src-exts types to Tidal's functions from time to values. So...

...while you could do this, if you really wanted to support interactive use in GHCI - and I really mean, typing into GHCI, not Atom or whatever: fast :: Exp SrcSpanInfo -> Exp SrcSpanInfo -> Exp SrcSpanInfo

...it would be simpler to:
(a) provide functions from Exp SrcSpanInfo (ie. your tree) to all renderable values of interest
(b) use parseExp from haskell-src-exts to get your tree 

Which is exactly what MiniTidal is already doing - taking a Tidal/Haskell tree and collapsing it into the normal Tidal functions from time to values... 

The only reason I can think of to not use haskell-src-exts for the "AST" is if the intention is to break the relationship between Haskell and Tidal. Which is another conversation, I guess?...

**Comment by yaxu** [comment]
Thanks @dktr0, I've looked at haskell-src-exts but didn't find a 'way in' in terms of documentation I could understand. I'll have a proper read of minitidal which will help!

Out of interest, what's stopping you from taking the list of type signatures and writing something to turn that into code so that minitidal can support everything?

I did notice that haskell-src-exts lost its maintainer recently, I don't know if that's a concern: https://mail.haskell.org/pipermail/haskell-cafe/2019-May/131166.html

As you imply I think supporting Tidal running in ghci isn't really the long term aim.

One thing I'd really like to do is have a reliable and fast way of comparing two expressions, to find out if one can be applied to the other, for a rewrite of Texture.

**Comment by dktr0** [comment]
Yes, I found the haskell-src-exts documentation a disincentive at first too (that's why I put off reworking MiniTidal in terms of it for so long!) - then realized I just needed to focus on the Exp type. The constructors look ugly because of the way location info is embedded in them, but in MiniTidal the ExpParser type in ExpParser.hs abstracts most of that ugliness away.

In answer to what's stopping us from taking the list of type signature (ie. via template Haskell) and turning them into MiniTidal? Just time and mental energy, really! I wanted to understand it without the extra layer of TH first. But I think that's the next step. There are some cases in particular it will make easier (when functions are added which have particular interweavings of Pattern a and Pattern (something concrete) this kind of propagates through the structure in mechanical ways that could be captured algorithmically).

Interesting to note about haskell-src-exts losing its maintainer, definitely something to stay abreast of. The suggestion there to use ghc-lib-parser is problematic for me - looks like that has a bunch of OS dependencies and ghc dependencies that I am pretty skeptical would transfer to the browser context... I tend to think/hope haskell-src-exts - as a text parser for a language whose basic spec hasn't changed much and isn't going to - should be usable without maintainer for a long time?

Yes, we could use MiniTidal now to find out if an expression can be applied to another. If you already somehow know the supposed type of the first algorithm then it is just parsing that one, parsing and applying the second one, and seeing if the whole thing succeeds. If you don't already know the type of the first algorithm then I think it would still work but would be rather less efficient: I think you'd attempt to parse all possible combinations (not as hard or slow as it sounds) and see which one succeeds. Something like:

runAndApplyExpParser :: ExpParser (a -> b) -> ExpParser a -> Exp SrcSpanInfo -> Exp SrcSpanInfo -> Either String b
runAndApplyExpParser fP xP fE xE = do -- in Either String monad
  f <- runExpParser fP fE
  x <- runExpParser xP xE
  return (f x) 

canParseTwoThingsInto :: Exp SrcSpanInfo -> Exp SrcSpanInfo -> Maybe String
-- String could be swapped for some more specific representation of the result, of course
canParseTwoThingsInto  e1 e2 = do -- leveraging Alternative instance of Maybe
  runAndApplyExpParser (parser :: Result (Pattern Int -> ControlPattern)) parser  e1 e2 >> return "Pattern Int -> ControlPattern" <|>
  runAndApplyExpParser (parser :: Result (Pattern String -> ControlPattern)) parser  e1 e2 >> return "Pattern String -> ControlPattern" <|>
 ...etc...

I think this would not be too computationally intensive. If it was to become too intensive, however, I think it would be possible to add a "preview" that speeds it up by peeking at the AST and making an "educated guess" about what the types are (eg. privileging the most common cases). But probably not necessary.

Would be fun to think about making Texture work in Estuary.... just sayin'!

**Comment by jwaldmann** [comment]
Hi. I didn't have time to follow this closely, but I am reading up.  What could I do to help?

For the current version of `TPat`, is there a function `print :: Show a => TPat a -> Show` that is, in some sense, the inverse of `parseTPat`? (I am trying https://github.com/jwaldmann/tidal-fuzz-test/blob/master/src/Sound/Tidal/PrintBP.hs but that's too simple.)

So you do want some form of typed lambda calculus here? but you don't want to use the GHCI API since that would not help with distribution/deployment?  (as importing a module in Hint requires that its .so files are present).

**Comment by yaxu** [comment]
I think this would require an extensive rewrite of tidal to explore, so am closing with the speculative tag for now.
