### ISSUE TITLE
Chords as numbers

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#258]
Within the sequence parser, you can already notate integers using note names (e.g. `cs` = `1`), howabout being able to also notate them with chord names (e.g. `cm7` = `[0,3,7,10]`) ?

**Comment by yaxu** [comment]
this could default to `c`, allowing you to also do things like `"maj m7" + "<c e f>"` instead of the current `(chord "major minor7") + "<c e f>"`

**Comment by jarmitage** [comment]
I like this a lot, feels like a natural progression from the current syntax!

**Comment by OscarSouth** [comment]
I recently put did something in Python which could be handy to borrow a little logic from, I'll post a few excerpts from a notebook file to demonstrate:

With another musical analytical goal in mind, I was generating dataframes of data & contextual metadata metadata on systematically generated pitch structures.  I also wanted to add humanly readable chord labels as a unique and quickly readable identifier.  This is a sample from the dataframe containing all columns, before chord labels were generated:

![image](https://user-images.githubusercontent.com/32574713/35856995-9c6864cc-0b2f-11e8-9570-1f5d7975475f.png)

The following mess of list comprehensions and ternary logic generates labels based on the 'pitch_int' column:

![image](https://user-images.githubusercontent.com/32574713/35857125-1171dd2a-0b30-11e8-8695-d414271cf809.png)

Labels that look like this are generated:

![image](https://user-images.githubusercontent.com/32574713/35857005-aad2da2e-0b2f-11e8-8f95-93d4194b55c3.png)

It will require a little more finesse (this was just a prototype, I didn't bother to implement sharps/flats, just went in one direction with it) and the bunch of list comprehensions that implement it isn't too tidy or efficient, but it correctly uniquely and generated the chord labels in a clear and readable way.  With only a little tweaking (currently it's working with 3 note structures) it would be capable of generating the labels for any possible combination of pitches.  Another area that I'm planning to expand it in is to also specify the inversions present in each structure.

I think in an implementation in TidalCycles where the chord labels are being read rather than being generated could be done pretty easily using the ternary logic which was used to generate the labels.  It took a while to get to a clean, readable, logical and uniquely identifying system of label generation working.  It could be simplified down in syntax for live purposes pretty easily too.

There could also be 'enharmonically equivalent' labels in TidalCycles, where different labels could result in the same chords due to sharps/flats or other kinds of notation anomalies.

Anyway I think that this was really just a long winded way to get to the point of "I can help out with labeling logic if that's helpful".

Another suggestion would be to implement a '[[functionality] of [chord]]' kind of thing.  For example, 1V could be V of C# (F#), diii (I used a note name rather than int this time) could be iii of D (F#m).  You'd need to add a few extra syntactical elements but it should be doable, here are some ideas:

Option A:  everything is based off the major scale (I, i, iii, IV etc. all build up the Ionian mode) and sharps/flats are specified.  IE:
2iii = F#m
dIII = F#
diii# = Gm (enharmonically equivalent to div/2iv)
2iiib = Fm

Tensions could be added according to the notation I discussed above.  This second (n of X) method is well suited for writing tonal progressions as it considers key centre, tonality and modulation in it's syntax.

Just some ideas/food for thought from a music analysis perspective.

**Comment by fdragovic** [comment]
sorry for not being helpful in any way but have to say that chord function
and being able to add patterns that simply now is awesome! thanks.
completely missed that (:

**Comment by yaxu** [comment]
Made some headway with this:
https://github.com/tidalcycles/Tidal/pull/364/commits/2910c7709e77bdfdd919268b0adef3f0bc13ed60

**Comment by yaxu** [comment]
I think this is solved with https://github.com/tidalcycles/Tidal/commit/6bbac2f8fe4c1b46d4a9c74d4ae4262225d9168c

The chord table probably isn't perfect though: https://github.com/tidalcycles/Tidal/blob/master/src/Sound/Tidal/Chords.hs#L113

**Comment by pd3v** [comment]
Playing:
`p "1" $ superimpose (arpg.(# n "'major7")) $ n "'major7" # s "superpiano" `
Should not `arpg` be running chord notes once per chord played?

**Comment by yaxu** [comment]
@pd3v you've start with four notes of a major7 chord, then in the superimpose, replace each of those four notes with the four notes of the same chord, ending up with 16 notes. Maybe you just meant this:

```
p "1" $ superimpose (arpg) $ n "'major7" # s "superpiano" 
```

**Comment by pd3v** [comment]
..but of course! And then if I want to transpose c major7 to, say g major7, and run an arpeggio over c major7 chord, I do : `p "1" $ superimpose (arpg.(+ n 7)) $ n "'major7" # s "superpiano"`
Niice...
