### ISSUE TITLE
Rhythmical behaviour

### ISSUE THREAD

**Issue by smrg-lm** [tidalcycles/Tidal#276]
[subject edited by me, It didn't look good, at all]

I don't know if this was already considered. I'm on last release (0.9 I think) and found some things I don't understand why are the way they are or if they are bugs.

On is that *almost* always a sequence is evaluated it starts at upbeat. Is that correct? Even time shifting the sequence I can't get a consistent behaviour, sometimes it does some times it doesn't. For me is kind of an important issue because it affects the way patterns are perceived if there is no previous context, e.g. upbeat becomes the beat reversing rhythmical meaning of the sequence.

Another thing is the / operation. Documentation says "slow down", "less often" and "every n cycle(s)". But here is the thing:

d1 $ sound "[bd sn] cp/2"

that sequence plays cp sample once every 2 cycles *but* keeping positional relationship to the sequence within the same grouping level, however:

d1 $ sound "[bd [hh hh:1]/2]"

alternates the steps of the sub-group the same way "<>" does, i.e. internal group don't keep positional relationship within the sequence the sub-group is part of, and:

d1 $ sound "[bd [hh hh:1]/3]"

adds yet another rhythmical behaviour, it does keep the positional relationship but alternating the appearance of the sub-steps every 3 cycles that is 1) "bd [hh ~]" 2) "bd [~ hh:1]" 3) "bd ~". [Edit: markdown cross out the text not me].

The last thing I can't sort is the sampler effects behaviour as someone else told me. If applying an effect affects every sequence in an orbit and by default every sequence is sent to the same orbit every superposed d-sequence should consistently have the same effect, but it happens that sometimes they do and sometimes they don't.

Hope my English is understandable, I like Tidal a lot.

**Comment by yaxu** [comment]
Hi smrg-lm, sorry for being very slow in this reply
This is all expected behaviour I think, so I will close this issue for now but feel free to continue to comment if something isn't clear.
`/` does indeed slow down the subpattern. With cp/2 you are running that step at half speed. The first time you get the first half which sounds, the second you get the second half which doesn't. The event must contain the start ('onset') of a sound otherwise no trigger message will be sent. I think this explains your other examples but again, shout if it isn't clear.
It's true that global effects are unpredictable if multiple patterns with different effect values are sent to the same orbit. For now the only way around this is to put patterns on separate orbits.
To be sure of making a change in a down beat, have a look at the transitions. There is quite a lot of latency in tidal at the moment so otherwise you have to hit eval quite a bit in advance. We should look at reducing this.

**Comment by smrg-lm** [comment]
Thank you for the answer, I see the math now and how it affects the rhythm, it does keep positional relationship but stretched and distributed in different cycles. I thought of "/" as only affecting the onset of the grouped pattern by distributing it in different cycles and not affecting its internal duration. That fragmentation of time relations is quite unusual, there is no wrong here.
