### ISSUE TITLE
chord does not work with choose

### ISSUE THREAD

**Issue by kasparsj** [tidalcycles/Tidal#280]
Hi, I'm trying to get some random chords, but given the example below, it looks like `slow `is ignored and all three chords are played on each step:

`m1 $ slow 4 $ note $ toScale Scales.major (chord $ choose ["major", "minor", "dom7"])`

**Comment by bgold-cosmos** [comment]
`choose` doesn't provide it's own "structure", you need another pattern somewhere to actually determine how often the chords play.  One way to do this might be something like
```
m1 $ note (struct "x/2" $ toScale Scales.major $ chord $ choose ["major", "minor", "dom7"])
```
where you can replace the "x/2" with whatever structure you want.

But another thing, I'm not sure `chord` and `toScale` are really meant to be mixed together like that.  `chord "major"` gives [0,4,7], i.e. CEG in the normal 12-tone scale, but using `toScale Scales.major` interprets those numbers instead of whole tones on the major scale, so you get CGC.  I'm not sure if that's what you intended.

**Comment by kasparsj** [comment]
Oh, great, thanks for the clarification.
