### ISSUE TITLE
Two samples as one

### ISSUE THREAD

**Issue by bgrange** [tidalcycles/Tidal#341]
Hello,
I'd like to treat a stack of two samples syntactically as one.
The specific case I'm dealing with is this:
I have this pattern:
d5 $ sound "bd bd ~ bd bd ~ bd ~ bd bd ~ bd bd ~ bd bd ~ bd"

and I want to layer a bottle sound on top of it with the same rhythm.

In general, I think there should be a way to create "virtual samples": things which can be manipulated like samples at the syntactic level but which are not necessarily in the Dirt-Samples directory. Created on the fly, during a live-coding session.

Like this:
createSample (sound "[bd, bottle]" # gain "1.3") "x"
OR
let x = virtualSample (stack [sound "[bd, bottle]" # gain "1.3")

And then:
d1 $ sound "x x ~  x x ~ x ~ x x ~ x x ~ x x ~ x"

**Comment by kindohm** [comment]
I think the main/easiest way to solve your problem is to separate your samples from the rhythmic structure:

d5 $ slow (9/4) $ gain "1 1 ~ 1 1 ~ 1 ~ 1 1 ~ 1 1 ~ 1 1 ~ 1" # sound "[bd, bottle]"

There's also the struct function. I don't use it very often but it might work:

d5 $ slow (9/4) $ struct "x x ~ x x ~ x ~ x x ~ x x ~ x x ~ x" # s "[bd, bottle]"

I'm not as sure about your question about "virtual samples" though. You can certainly use variables to store patterns or structures:

let pat = "1 1 ~ 1 1 ~ 1 ~ 1 1 ~ 1 1 ~ 1 1 ~ 1"
let sounds = "[bd, bottle]"

d5 $ slow (9/4) $ gain pat # s sounds

and:

let g = gain pat
let sss = s sounds

d5 $ slow (9/4) $ g # sss

^^ haven't tested that, hopefully it works :)

-Mike

-- 
  Mike Hodnick
  mike@kindohm.com

**Comment by yaxu** [comment]
A small correction on the `struct` example:
`d5 $ slow (9/4) $ struct "x x ~ x x ~ x ~ x x ~ x x ~ x x ~ x" $ s "[bd, bottle]"``

**Comment by yaxu** [comment]
I'll close this for now, feel free to open if you think things could be improved @bgrange

**Comment by bgrange** [comment]
Thank you
