### ISSUE TITLE
What does a reverse/inverse sawtooth look like

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#342]
Here's a conundrum..

`query saw (0,0)` == 0

Fair enough. but..
`query (rev saw) (0,0)` == 0

I was expecting 1.. But this does make sense, `saw` approaches 1 but never gets there, by reversing it you just swap `(0,0)` for `(1,1)`, which is also 0. This works:

`query ((1-) <$> saw) (0,0)` == 0

So I guess we just have to define `isaw` or something as `((1-) <$> saw)`?

**Comment by telephon** [comment]
Maybe there is a semantic issue about the range of a cycle? It becomes apparent when you reverse the cycle. Logically in a cycle `0 == 1`, because `0 ≣ 1 mod 1`. So when you map the point `0 == 1` to the point `1 == 0`, nothing changes, in a sense. But somehow, the idea of a reversal distinguishes the two appearances of the same value, so the direction of time somehow must become part of what tidal returns here as the actual (apparent) value?

**Comment by bgold-cosmos** [comment]
Would viewing an Arc as a "closed, open" interval make this more clear?  I think part of the issue is that we treat a full cycle event as if it takes place "from 0 to 1" when really the interval is [0,1).  I think it's sensible for the "per-cycle reverse" of that to be [0,1).

In other words, there's a distinction between "cycle value 1, as the beginning of an event" which `rev` moves to "cycle value 2, as the end of an event",  and "cycle value 1, as the ending of an event" which `rev` moves to "cycle value 0, as the beginning of event".
