### ISSUE TITLE
Conditional Modulations

### ISSUE THREAD

**Issue by cannc4** [tidalcycles/Tidal#345]
I find this function written by @bgold-cosmos to be super useful and it might be a good idea to take a look at its inner workings. It's sort of an hacky `conditional` function

```
modNote n f p = stack [f $ filterValues (isEq n . (Map.!?n_p)) p,filterValues (not . isEq n . (Map.!?n_p)) p] where isEq a m = (isJust m) && (a == (fromJust $ fromV $ fromJust m))

modValues par test f p = stack [ f $ filterValues (test' . (Map.!?par)) p, filterValues (not . test' . (Map.!?par)) p ] where test' m = (isJust m) && (test (fvalue $ fromJust m))
```

**Comment by yaxu** [comment]
I think this _might_ be a problem for Haskell's lenses to solve, but I'm not sure as I don't understand lenses just yet..

Perhaps for now we should just include these functions as-is. I propose renaming them to avoid confusion with modulo. Perhaps `withNote` and `withControl`?

**Comment by yaxu** [comment]
We have two approaches to this:
https://github.com/tidalcycles/Tidal/pull/392

- `withControlValue`, `withControlValues`, and `withControlRange`: https://github.com/tidalcycles/Tidal/pull/392
- `fix`, `unfix` and `contrast`: https://github.com/tidalcycles/Tidal/commit/55ee834048386450d3fcf5e71143dc3cefb089db

I think `fix` is more flexible and easier to use than `withControlValue`.
```
d1 $ withControlValue "n" 3 (# crush 3) $ s "supermandolin" >| n "1 2 3"
d1 $ fix (n 3) (# crush 3) $ s "supermandolin" >| n "1 2 3"
```
It might be best to only go with `fix` et al for simplicity and patternability, but it probably can't support all the features of `withControlValue` et al.. Thoughts?

**Comment by bgold-cosmos** [comment]
(continuing discussion from #392)

TolerantEq is in Pattern.hs, line 214 I think.  I think your implementation of fix is structurally the same as what I was calling `whereCV`, for reference:
```
maskr pb p = filterJust $ filt <$> pb Sound.Tidal.Context.*> p where
  filt True b = Just b
  filt False b = Nothing

whereCV m f p = stack [
  f $ maskr pb p,
  maskr (fmap not pb) p
  ] where
    pb = liftA2 (~==) m p
```

something like `withControlValues` seems like it should be implementable in terms of `fix`, although getting it to work with flexible types seems tricky.   For the record, it's not as simple as `fix (n "[2,3]")` because that actually stacks up multiple copies of events.  My first attempt is:
```
withCVs par xs f = apf [whereCV (pS par $ pure x) f | x <- xs] where
  apf [f] x = f x
  apf (f:fs) x = f $ apf fs x
```
(I feel like `apf` is reinventing something in Prelude, but I couldn't figure it out in terms of foldr)
but with the `pS` in there this is restricted to strings at the moment.

**Comment by yaxu** [comment]
Ah sorry, forgotten about `TolerantEq`! But that's supposed to just account for floating point error and otherwise do an exact match, so actually `liftA2 (~==) (s "a") (s "a" # n "1")` should be false.. So you're exploiting a bug there :) 

I think I only had tests in mind for `TolerantEq`, I think using it in Tidal should probably be avoided.. Where floating point error becomes an issue, we should move to a less problematic type (as with rational time).

It'd be interesting to profile the two approaches. I've rarely profiled anything in tidal but think cpu is going up with the much faster calculation rate in 1.0.

**Comment by yaxu** [comment]
@bgold-cosmos I'm feeling that exploiting polyphony for this might be the wrong approach. Perhaps we need to instead use `Pattern [a]`, and implement something in the parser for parsing into that. However since `[]` is already taken I'm not sure what we could use to delimit lists of values.. Maybe `()`..

**Comment by bgold-cosmos** [comment]
I was thinking that since things like `n ("1" + "2 3")` and `n "1" + n "2 3"` already both work (i.e. `+` works on both Patterns and ControlPatterns), then if there's a way to sensibly define `==` for patterns then all this functionality just collapses into `filterValues` itself, no need for separate functions.

**Comment by bgold-cosmos** [comment]
Ah, and the "bug" with `~==` is that `Map.differenceWith` returns things in the first map not in the second, but not vice versa.

**Comment by yaxu** [comment]
I can't think of a sensible definition of `==` for patterns as we'd want the output to be `Pattern Bool`

I added `contrastBy` which should be able to make `fixRange` that takes a pattern of ranges.. Got to sleep now though!

**Comment by bgold-cosmos** [comment]
OK!  I've made use of `Pattern Bool`s before, though they're a bit weird.  I've been tinkering around and came up with this notation:
```
tidal> a --> b = (snd $ head $ query a (State (0,1) Map.empty)) `Map.isSubmapOf` b
tidal> filterValues (n "1" -->) $ n "1 2 3" # s "foo"
(0>⅓)|n: 1.0f, s: "foo"
```

**Comment by yaxu** [comment]
I made `fixRange`, `fixValues` and friends
https://github.com/tidalcycles/Tidal/commit/8d57fe38c558805d720bbb5fe088b4d9e8fbfb38
https://github.com/tidalcycles/Tidal/commit/5be0a185e74cbc2db90b3bb65312f9e9e79d1ab1
https://github.com/tidalcycles/Tidal/commit/ccf84775c67eac6c17fd3069929b51bf96a068a9

We still lack a nice way to make controlmaps with tuples/lists in, but good for a proof-of-concept.

**Comment by yaxu** [comment]
I think we should probably go with the more patternish `fix`, `unfix` and `contrast`. This means we could also drop the `Valuable` class for now.

**Comment by yaxu** [comment]
Thinking about the usability of this a bit..
```
fix (|+ n 1) (n "1 ~") $  s "bd" >| n "1 4"
```
gives `2 ~`, but you might expect it to give `2 4`

Likewise
```
fix (|+ n 1) (n "[1,2]") $  s "bd" >| n "1 4"
```
gives `[1,2] [4,4]`, but you might also expect it to give `2 4`

I think this boils down to a general problem with `*>` - we say it takes structure only from the right, but this is only in terms of time, not in terms of polyphony (searching for a better word for this).

It makes some sense that `"[1,2,3,4]" +| "1"` results in `[2,3,4,5]`, but less sense in the context of `fix`.. Would be good to get to the bottom of this..

**Comment by yaxu** [comment]
Ok with https://github.com/tidalcycles/Tidal/commit/56f68e33bfe7a2d92bc16f205d005b473cbc52d5 the matching for `fix` is fuzzier, as per the previous comment. It'd be good to think about what's going on with this more, as this approach might be useful in other ways, or might turn out to be a Bad Idea (as it is conflating polyphony with something else, after all..).
I've removed `withControlValue` and friends, and the supporting `Valuable` typeclass for now, as `fix` seems a more patternish approach.
There isn't really a UI for dealing with ranges to make `fixRange` useful, but I think that's one for another ticket, as that would be useful for patternifying `within`, for example. So closing for now.
Thanks a lot for your work on this @bgold-cosmos !
