### ISSUE TITLE
Template haskell for little languages?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#375]
I'm looking into Template Haskell a bit. Currently our little sequence language for sequences (the stuff between double quotes) parses to our own AST.

How about we change it so it compiles to a template haskell syntax tree instead?

I'm struggling to understand template haskell (e.g., via https://www.schoolofhaskell.com/user/marcin/quasiquotation-101), but as far as I can tell, this would mean:
- compile-time type checking for sequences (not sure of the real world advantages of this..)
- More introspection around parsing sequences, in particular knowing where in the source a sequence is, which would probably help a lot towards solving #245
- being able to embed sequences inside other sequences, e.g. 
```
one = [bp|"a [b c] d"|]
two = [bp|$one [b c $one]"|]
```

The disadvantage is the heavier `[bp||]` rather than `""` syntax. I don't know for sure whether it's possible to get string overloading working with template haskell thing, but I'm guessing not.

Related - #370

**Comment by d0kt0r0** [comment]
I'm not sure but my intuition is that you don't need TH for any of those things. Another possibility is to take advantage of the combinatorial parsing style with Parsec - no intermediary AST at all then, just different parsers that are combined. MiniTidal shows an example of this approach already (although for sure there's lots of room to upgrade error reporting in it). I believe you can get the embedding thing by using a ParsecT type with state. I'd also note that this direction *may* work (or tend to work?) against binary redistributables of Tidal. There might be a tradeoff of making things more abstract/flexible versus making things more accessible here...

**Comment by bgold-cosmos** [comment]
I don't know if you need TH, but it already does a few of those things fairly handily, I think you can re-use Tidal's parser code without much change, and there are some aspects of it that could be very nice (splicing).  What I'm not clear on is if quasiquoting requires the `[blah|this that|]` syntax or if it's possible to combine with string overloading so that `""` automatically invoke the quasiquoter.  Probably not, but I can't find any mention either way.  I'm going to try a few tests...

**Comment by d0kt0r0** [comment]
Using TH for parsing in a live context might mean Estuary and Tidal development would have to part ways as I'm really not sure how much (if any) TH we would be able to support in the browser runtime environment.

**Comment by yaxu** [comment]
The parsing would still be done by Parsec, so I don't think this is an either/or, @d0kt0r0 . I don't fully understand things but think we could for example keep the current AST and then have an optional extra step to turn it into TH stuff.

You can find out the position of something in Parsec, but not relative to the haskell source file, as far as I know. TH can help with that.

It'd be interesting to learn more about things that are possible in good ol' parsec that we're not making use of, though..

@bgold-cosmos Good stuff, yes I agree it's probably not possible for the string overloading to invoke quasiquoting, but worth a go..

**Comment by d0kt0r0** [comment]
re: "You can find out the position of something in Parsec, but not relative to the haskell source file"... unless you are parsing *everything* with parsec (as in MiniTidal, for example, instead of ghci), then the position from Parsec's standpoint is the position in the whole. I think we might be surprised at how many idioms could be added to a parser like MiniTidal - I'm pretty sure the desiderata at the top of this thread can be straightforwardly accommodated that way. MiniTidal itself could be rewritten in TH to eliminate much of the boilerplate stuff, by the way. If you had MiniTidal rewritten in TH then there would be no TH in the runtime environment but because everything is parsed with one big Parsec parser you would have all the nice things...

**Comment by yaxu** [comment]
A thought - you can put parsebp in a TH string, but that doesn't buy you anything, because you can't embed one pattern in another, because a pattern isn't a datastructure. An AST is though, so having a TH shorthand for generating a mininotation AST could be useful., so you could do

```
foo = [bp|1 [2 3] 3|]
bar = [bp|3 4 ${foo}|]
```

**Comment by dktr0** [comment]
Wrong tool for the job, IMHO - and also won't transfer to settings like Estuary - also not sure how well it transfers to interpreted settings at all (given TH's two pass compilation in separate modules thing)

**Comment by yaxu** [comment]
Lets just keep #370
