### ISSUE TITLE
improve API documentation (explain the basic model)

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#4]
yes I know no Haskell programmer likes to do this because the code is usually shorter than its specification. but - take, e.g., the `Pattern` type. This seems to be the fundamental abstraction. But the API docs do a bad job of explaining it. http://hackage.haskell.org/package/tidal-0.2.7/docs/Sound-Tidal-Pattern.html#t:Pattern 

I see that a pattern is a (contains a) mapping from `Arc` to list of events. I see `Arc = (Time,Time)` but I have to guess that it denotes an interval. But how exactly, is it
`(start, end)` or `(start, duration)`? (do you make a distinction between time and duration?) Now, `Event a = (Arc,a)`.  Again, it's not immediately obvious why this should be called Event (in fact it is not obvious at all - I'd expect that an Event occurs at a point in time, and has no duration). Also, what should be the invariant for the various Arcs (in the Events that make up a Pattern) - should they be disjoint? In some way successive?

I think that some explanation on the basic types would help (me) a lot to understand the model, and this in turn would help in using the language/interpreter, and also in extending it.

**Comment by lennart** [comment]
@jwaldmann Concerning haddock, do you know of an automated way to let haddock generate just markdown snippets of the function documentation? Is there a programmatical way to adjust the rendering of documentation? We were talking about generating the reference documentation from source and I just _hacked_ up a shell script to do that. I wonder if there is some kind of easier way, since the rest of the documentation (the non-API parts) live in a [github-page built through jekyll](http://tidal.lurk.org)

If you are experienced with haddock please tell me, I haven't been using up to now.

**Comment by yaxu** [comment]
I'll close this for now, there is more info inline now, the FARM paper from a while back and I'll write a new paper soon too.
