### ISSUE TITLE
The structure of adding nothing

### ISSUE THREAD

**Issue by bgold-cosmos** [tidalcycles/Tidal#406]
This behavior seems a bit confusing to me:

`("1 2 3" |+ "0 ~ 2")::(Pattern Int) -> "1 ~ 5"`

That seems an understandable result for `+|` and maybe `|+|`, but it's not what I expected for `|+`.

**Comment by yaxu** [comment]
Hm, what result did you expect?

**Comment by bgold-cosmos** [comment]
Whoops, meant to say :).  I expected the structure on the left, which would be `"1 2 5"`

The specific case where this came up was where I was trying to `"c*8" |+ "[g(5,16)]/2"`.  I understand `efull` eventually solves that particular issue, but I thought I could get around it by using the "structure-on-the-left" operator `|+`.

**Comment by yaxu** [comment]
Yes true, for operators like `+` that are `a -> a -> a`, we could say that if only one of the values exists, keep the original, without adding anything to it. 

However this will often not be what you intended. Lets think on this one..

**Comment by yaxu** [comment]
Coming back to this, I think the current definitions of `|+` and friends is fine really. We could have alternative operators which preserve unmatched values, but it just feels a bit messy. I think better to think about alternative an euclidean patterning that doesn't leave gaps, e.g. makes `"x _ _ x _ _ x _"` rather than `"x ~ ~ x ~ ~ x ~"`. I can't think of nice mini notation syntax for that, though.

**Comment by kindohm** [comment]
Something like these?

```
d1 $ s "bd|3,8|"

d1 $ s "bd/3,8/"
```

**Comment by yaxu** [comment]
Closing for now, I think use of binary/boolean patterns are probably the way to go with this sort of thing. Please reopen if you disagree.
