### ISSUE TITLE
nonrealtime synthesis (output to audio file)

### ISSUE THREAD

**Issue by jwaldmann** [tidalcycles/Tidal#410]
**Describe the function/feature you'd like**

I want to render the sound of a tidal pattern (set) to an audio file, for a given length of time.
I want to call this function programmatically, that is, from inside a ghci session.

**Describe alternatives you've considered**

It seems possible to dump audio from the SC IDE. I don't want to mouse around in the IDE,
in fact, I don't even want to start it (I am using `sclang dirt_startup.scd`).

**Additional context**

SC has a function for NRT http://doc.sccode.org/Guides/Non-Realtime-Synthesis.html, we just
need a Haskell wrapper for that. If it's clear what to do, I can try to do it.

**Comment by jwaldmann** [comment]
this? https://github.com/musikinformatik/SuperDirt/blob/master/hacks/chunk-recorder.scd

**Comment by gilfuser** [comment]
There's also "function hacks". Probably useful for that case.

**Comment by yaxu** [comment]
Is this a live issue?

**Comment by yaxu** [comment]
I use the ecasound commandline utility for this. Otherwise, adding something on the supercollider/superdirt side would be the answer. Closing this here for now.

**Comment by telephon** [comment]
If tidalcycles could write a file with all the OSC-messages it would have sent to superdirt, superdirt could load that, and then render a score for NRT-synthesis from it. There are some issues that would need care: you'd need to add the soundfile load to the start, and the synthdefs (in brute force, all of them). Then, collecting all the messages are easy, since they are time stamped.

It is feasible, but I don't have the time for it. I can give hints and help.
