### ISSUE TITLE
Pattern begins from different point

### ISSUE THREAD

**Issue by ligoism** [tidalcycles/Tidal#442]
**Describe the bug**

When I try to run simple pattern like this: _**d2 $ sound "[bd bd hh hh]"**_, it's always begin from different point. Sometimes it's begin from _**bd**_ sound, sometimes it's begin from _**hh**_. When I run 2 patterns together they are synchronised normal. Is this behaviour normal? And this behaviour is the same for all types of patterns when I use _**[ ]**_. 

**Steps**

1. I press **_Ctrl+Enter_** - pattern begins from different point.
2. Stop with _**hush**_.
3. Press **_Ctrl+Enter_** again - pattern begins from different point again, not from the first point.

**Expected behavior**

I think pattern must begin from the first position. it's looks strange for melody. Melody always begins from different point.

**Environment (please complete the following information):**

 - OS: Windows 10
 - Haskell version 8.4.3 FULL
 - Tidal version 1.0.5
 - SuperCollider 3.10.0

**Comment by yaxu** [comment]
Hi @ligoism,

Interesting question.. The problem here is that the cycles are running all the time in the background, so when you run two patterns they are indeed in sync. When you stop them and start them, it is indeed difficult to impossible to time it so you start at the start of a cycle.

I think what we need here is a way to both reset the clock and start a pattern at the same time. This is sort of possible with this:
```
do resetCycles
   d1 $ sound "bd sn"
```
but that's not super accurate either.

**Comment by ligoism** [comment]
Yes, **_resetCycles_** is not super accurate too. But I understood that this behaviour is normal for this time. Ok. Thanks a lot for answer.

**Comment by yaxu** [comment]
It'd be nice if this was accurate, at least:
```
cps 0
resetCycles
setcps 1.1
```

**Comment by yaxu** [comment]
There is `qtrigger` now

```
d2 $ qtrigger 2 $ sound "[bd bd hh hh]"
```
