### ISSUE TITLE
Cabal install

### ISSUE THREAD

**Issue by tom-christie** [tidalcycles/Tidal#45]
The basic 'brew install cabal-install' is producing a cabal that won't run on OS X Yosemite. It seems to work better if you install from source:

```
brew install --build-from-source cabal-install
```

Found the suggestion here:
https://github.com/Homebrew/homebrew/issues/33314

I just thought you might want to update your install-osx.md!

**Comment by robjac** [comment]
+1

**Comment by robjac** [comment]
Unfortunately, after having tried the above, I am still getting the same errors with cabal install tidal   ; all of this because I updated Yosemite to 10.10.2. 

☁  Dirt [master] brew install --build-from-source cabal-install
==> Installing cabal-install dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/xz/5.2.1
==> make install
🍺  /usr/local/Cellar/xz/5.2.1: 59 files, 1.7M, built in 54 seconds
==> Installing cabal-install
==> Downloading https://hackage.haskell.org/package/cabal-install-1.22.0.1/cabal-install-1.22.0.1.tar.gz
######################################################################## 100.0%
==> sh bootstrap.sh --sandbox
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cabal-install/1.22.0.1: 6 files,  23M, built in 23.0 minutes
☁  Dirt [master] cabal update
Downloading the latest package list from hackage.haskell.org
☁  Dirt [master] cabal intall tidal
cabal: unrecognised command: intall (try --help)
☁  Dirt [master] cabal install tidal
Resolving dependencies...
Configuring mersenne-random-pure64-0.2.0.4...
Building mersenne-random-pure64-0.2.0.4...
Preprocessing library mersenne-random-pure64-0.2.0.4...
clang: warning: argument unused during compilation: '--param max-inline-insns-single=1800'
clang: warning: argument unused during compilation: '--param max-inline-insns-single=1800'
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
linking dist/build/System/Random/Mersenne/Pure64/Base_hsc_make.o failed (exit code 1)
command was: /usr/bin/gcc dist/build/System/Random/Mersenne/Pure64/Base_hsc_make.o dist/build/System/Random/Mersenne/Pure64/Base_hsc_utils.o -o dist/build/System/Random/Mersenne/Pure64/Base_hsc_make -m64 -L/Users/robjac/.cabal/lib/x86_64-osx-ghc-7.8.4/random-1.1 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/time-1.4.2 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/old-time-1.1.0.2 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/old-locale-1.0.0.6 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/deepseq-1.3.0.2 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/array-0.5.0.0 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/base-4.7.0.2 -liconv -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/integer-gmp-0.5.1.0 -lgmp -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/ghc-prim-0.3.1.0 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/rts-1.0 -lm -ldl
Failed to install mersenne-random-pure64-0.2.0.4
Configuring network-2.6.0.2...
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
checking build system type... x86_64-apple-darwin14.1.0
checking host system type... x86_64-apple-darwin14.1.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for unistd.h... (cached) yes
checking winsock2.h usability... no
checking winsock2.h presence... no
checking for winsock2.h... no
checking ws2tcpip.h usability... no
checking ws2tcpip.h presence... no
checking for ws2tcpip.h... no
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking for readlink... yes
checking for symlink... yes
checking for struct msghdr.msg_control... yes
checking for struct msghdr.msg_accrights... no
checking for struct sockaddr.sa_len... yes
checking for in_addr_t in netinet/in.h... yes
checking for SO_PEERCRED and struct ucred in sys/socket.h... no
checking for getpeereid in unistd.h... checking for getpeereid... yes
checking for _head_libws2_32_a in -lws2_32... no
checking for getaddrinfo... yes
checking for gai_strerror... yes
checking whether AI_ADDRCONFIG is declared... yes
checking whether AI_ALL is declared... yes
checking whether AI_NUMERICSERV is declared... yes
checking whether AI_V4MAPPED is declared... yes
checking whether IPV6_V6ONLY is declared... yes
checking whether IPPROTO_IP is declared... yes
checking whether IPPROTO_TCP is declared... yes
checking whether IPPROTO_IPV6 is declared... yes
checking for sendfile in sys/sendfile.h... no
checking for sendfile in sys/socket.h... yes
checking for gethostent... yes
checking for accept4... no
configure: creating ./config.status
config.status: creating network.buildinfo
config.status: creating include/HsNetworkConfig.h
config.status: include/HsNetworkConfig.h is unchanged
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
Building network-2.6.0.2...
Preprocessing library network-2.6.0.2...
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
linking dist/build/Network/BSD_hsc_make.o failed (exit code 1)
command was: /usr/bin/gcc dist/build/Network/BSD_hsc_make.o dist/build/Network/BSD_hsc_utils.o -o dist/build/Network/BSD_hsc_make -m64 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/unix-2.7.0.1 -ldl -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/time-1.4.2 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/old-locale-1.0.0.6 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/bytestring-0.10.4.0 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/deepseq-1.3.0.2 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/array-0.5.0.0 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/base-4.7.0.2 -liconv -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/integer-gmp-0.5.1.0 -lgmp -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/ghc-prim-0.3.1.0 -L/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/rts-1.0 -lm -ldl
Failed to install network-2.6.0.2
cabal: Error: some packages failed to install:
hosc-0.14.1 depends on network-2.6.0.2 which failed to install.
mersenne-random-pure64-0.2.0.4 failed during the building phase. The exception
was:
ExitFailure 1
network-2.6.0.2 failed during the building phase. The exception was:
ExitFailure 1
tidal-0.4.30 depends on network-2.6.0.2 which failed to install.
websockets-0.9.3.0 depends on network-2.6.0.2 which failed to install.




Wonder what went wrong?

**Comment by lennart** [comment]
Just a guess,

assuming you installed ghc via homebrew, 

I also had to install gmp which is what the error refers to: "ld: library not found for -lgmp”

so:

brew install gmp

and then proceed as before.

**Comment by robjac** [comment]
Thanks for the reply,
I already have ghc-7.8.4 and gmp-6.0.0a installed via homebrew. 

So I double checked, and tried ```cabal install tidal``` , and still the same problem. (still "ld: library not found for -lgmp”)


How would one re-install tidal fresh? (Maybe this would jogs something back into place).

cheers
-robbie jacobs

**Comment by bgold-cosmos** [comment]
This is a shot in the dark, but you might try telling cabal to install an older version of "network".  I don't think Tidal needs 2.6.0.0 -- I've got 2.4.2.3 and everything works OK for me.

**Comment by robjac** [comment]
I'll give it a shot. 

Everything WAS working perfectly for me; but the 10.10.2 Yosemite update really f*cked up my system. Sure it wasn't the update's 'fault'. 
 It took me a few days to fix permissions via 'single-user mode' (namely homebrew's usr/local/bin treachery which was causing Yosemite to hang/freeze at 50% of update/installation)

I suppose I'm wondering if anybody has had success with re-installing tidal from scratch; removing, uninstalling, reinstalling etc, and what the proper way/order to do it would be. 

I of course know how to do the above; but I'm just curious to hear from anybody else. 

cheers
-rob

**Comment by bgold-cosmos** [comment]
I haven't had problems recently, but I use MacPorts instead of homebrew.  So reinstallation is pretty much 1) blow away everything in `/opt/local` and `~/.cabal`, 2) follow the regular install instructions.

**Comment by robjac** [comment]
I did a full reinstall and same problem. 

tried to install older version of ```network``` and still:
```ld: library not found for -lgmp```

but i have gmp-6.0.0a installed.

**Comment by lennart** [comment]
Maybe this solution helps:
https://github.com/Homebrew/homebrew/issues/35203#issuecomment-72242958

It seems to be related to having gmp installed in user space and cabal installed not finding the installed gmp lib (from what I've there)

wonder how it worked in my case…

**Comment by robjac** [comment]
Just wanted to update: managed to get a successful install

It seems like cabal has been updated; and something was fixed for me in the process. 

I still have my Terminal trace, if anyone is interested. I'll try to make a copy to keep on hand. 

cheers. 

so happy to be back in Tidal world and now with Atom.io as my text editor and eval environment.

**Comment by jannacek** [comment]
Hi!! so i dont know how to do a full re-install :(  after updating to sierra tidal isnt working anymore, i get error:
events.js:160
Hide Stack Trace
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:286:12)
    at REPL.stdinWrite (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:72:25)
    at REPL.tidalSendLine (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:76:14)
    at REPL.tidalSendExpression (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:81:14)
    at doIt (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:130:18)
    at REPL.evalWithRepl (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:134:9)
    at REPL._eval (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:107:14)
    at atom-text-editor.tidalcyclesEval (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:29:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

Tried reinstalling atom, but to no avail.... 
help please?
I'm missing tidal, we had just met....

**Comment by vivid-synth** [comment]
Maybe it's easier to install the whole haskell platform (This is ghc+cabal+a few others)? I.e.:

```
brew cask install haskell-platform
```

(From https://www.haskell.org/platform/#osx )
