### ISSUE TITLE
"inverse" patterns from 0.9 do not work

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/Tidal#456]
**Describe the bug**
Old code that used `let inv 0 = 1` and `gain (inv <$> "0 0 1 1"` no longer works in 1.0.6

**To Reproduce**

```
let pat = "1 1 0 0"

let inv 0 = 1

let inv 1 = 0

d1 $ gain (inv <$> pat) # s "bd"
```

The `d1` line fails with:

`Failed to send. Is the 'SuperDirt' target running?`

**Expected behavior**

A pattern that sounds like `gain "0 0 1 1" # s "bd"`

**Environment (please complete the following information):**
 - OS: MacOS
 - Haskell version: 8.4.3
 - Tidal version: 1.0.6
 - SuperCollider version: 3.9.3

**Comment by bgold-cosmos** [comment]
The error message is weird, but I think the problem is you can't define `inv` in two separate `let` evaluations like that.  It has to be a multiline block, evaluated at once, to work properly.  So
```
let inv 0 = 1
    inv 1 = 0
```
works for me.  I think the quickest way to check is to try evaluating just `gain (inv <$> pat)` - it'll show a pattern if `inv` is defined properly, but return all sorts of errors if it isn't.

**Comment by yaxu** [comment]
`inv` needs defining in one go
```
let inv 1 = 0
    inv 0 = 1
```

**Comment by yaxu** [comment]
Sorry didn't see your message @bgold!

**Comment by yaxu** [comment]
(There is a more general problem with exception handling here too)

**Comment by kindohm** [comment]
Ha, weird. I have it defined with one `let` in my own "functions" file but when the question came up on talk.lurk.org I just manually eval'd each `inv` separately to quickly try it out. Thanks for clearing this up!

**Comment by tomasraposo** [comment]
I've evaluated in a multiline block and still got the same error ...
