### ISSUE TITLE
Monotonic shared clock

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#491]
Currently the system clock is the reference clock, which can be a problem if e.g. ntpd is running in the background on an unreliable WAN. We should switch to monotonic clock instead, e.g. via https://hackage.haskell.org/package/clock-0.7.2/docs/System-Clock.html 

This presents the problem of how to synchronise with others. Carabiner looks like an easy way forward: https://github.com/Deep-Symmetry/carabiner

**Comment by yaxu** [comment]
Since supercollider and osc in general works with NTP timestamps relative to a fixed epoch, I guess if we switch to a monotonic clock we'd need to continually call gettimeofday or whatever to calculate the timestamp.

**Comment by yaxu** [comment]
@telephon how does supercollider deal with this, does ntpd cause fluctuations/discontinuities in timing?

**Comment by dktr0** [comment]
EspGrid uses the monotonic clock - and using its query functions that return values relative to that clock is in theory the best way of using it. Because in practice so few environments / applications use the monotonic clock (some can't even get at it at all) EspGrid also provided clock query functions that return the same information in terms of system time, and for better or worse those functions have been used more...

**Comment by dktr0** [comment]
That aside however, it's not immediately clear to me that using the monotonic clock is necessarily the solution to the problem here. Since ultimately effects in the real world are up to SuperCollider and its scheduling system and clocks etc. An alternative path to working with the monotonic clock is to have the render system notice and take action when time advances or regresses in unusual ways. With Estuary, we have to do this - there is no access to the monotonic clock in the browser and it's super easy for people to do things that interrupt computation. So, when the current time is too much out of sync with what we expected it to be, we change our expectation.

**Comment by yaxu** [comment]
Yep I think this is the wrong way to go.
