### ISSUE TITLE
Combining patterns still not quite right

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#533]
For this:
```
Prelude Sound.Tidal.Context> "1" |+ "2 ~" :: Pattern Int
(0>1)|3
```
I'd expect to only get half the event, e.g. `(0>0.5)-1`

Likewise (and more seriously), this currently doesn't give any events:
```
Prelude Sound.Tidal.Context> "1" |+ "~ 2" :: Pattern Int
```
But I'd expect the second half of one, e.g. `0-(0.5>1)`

I noticed this as a problem because this doesn't work as expected:
```
# gain (sew "t(3,8)" 1 0.5)
```
yes this does:
```
# gain (sew "t(3,8)" "1*8" "0.5*8")
```

**Comment by bgold-cosmos** [comment]
It's a bit odd, but the first one seems correct to me.  `|+` means structure comes from the left, so `"1" |+ "2 ~"` has to have the structure `"x"`, and having 3 as the value doesn't seem crazy since the onsets coincide.

`"1" |+ "~ 2"` again has to have the structure `"x"`, and I guess the issue is that the value "1 + ~" is taken to be Nothing, when that's probably not the intent.

But it sounds like what you expect is closer to `+|` rather than `|+`?

**Comment by yaxu** [comment]
Here's a go at this:
https://github.com/tidalcycles/Tidal/commit/59deba51463ff386340d7e81a7221c02a13814dc

Now it's not really the structure that comes from the left with `|+`, but the *wholes*. That's the only difference between `<*` and `<*>` now. The parts are simply the intersection of the left and right.

The behaviour is mostly the same as before, because where the whole comes from also governs where the onset comes from.. If the whole comes from the left, then no onset can come from the right, unless it matches with an onset on the left.

**Comment by yaxu** [comment]
I think this is the way forward, so will close this for now.

**Comment by yaxu** [comment]
Here's a quick visualisation showing what happens now:

!["1 2 3" |+ "4 5"](https://user-images.githubusercontent.com/27940/60846589-d4b23480-a1d7-11e9-97b2-4c2c9327f521.png)

!["1 2 3" +| "4 5"](https://user-images.githubusercontent.com/27940/60846591-d7ad2500-a1d7-11e9-9141-5623fe418f69.png)

!["1 2 3" + "4 5"](https://user-images.githubusercontent.com/27940/60846537-ab91a400-a1d7-11e9-9034-84d8bf1b5f86.png)
