### ISSUE TITLE
Safety limits

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Tidal#588]
Ref: https://github.com/tidalcycles/Tidal/pull/586 from @dktr0 

Proposes a `vol` alias to `gain` that adds safety limits (0 to 0.999).

There are other explosive parameters, e.g. `shape` (1 or more gets LOUD), `room`/`delay` (feedback), and filters like `lpf`/`hpf` that can blow up.

It can be fun/musical to ride the limiter etc, but on the other hand unintended spikes can ruin ensemble performance and be dangerous on headphones and large systems.

Potential approaches:
1. Limit parameter range on in the synth side (superdirt/webdirt etc) - makes some sense for this to be limited/configured on the sound side, but duplicates work
2. Limit parameter range in the Tidal code - add more aliases
3. Limit parameter range in BootTidal.hs - make `gain` etc default 'safe', and configurable there
4. Make the current DSP limiter in the audio safer by default (and generally configurable - ref https://github.com/musikinformatik/SuperDirt/issues/137 )

**Comment by yaxu** [comment]
I think 3. should be an option if people want to do that, but 2. seems like the wrong place to do this. I think it's up to a synth to interpret values that work with how things are implemented.

So I think I favour doing both 1. and 4.

**Comment by yaxu** [comment]
It would still be good to consider `volume` vs `gain` and whether they could mean something a bit different with different curves and whatnot. I think MIDI velocity should also probably become its own parameter as a lot of synths have separate volume parameter(s).

**Comment by yaxu** [comment]
BTW I think probably the only time when you wouldn't want sensible limits on `gain`, `shape`, dsp safety limiter etc is recording for later mastering.

**Comment by telephon** [comment]
Re 1) if you make a list of limits, I'll add them to superdirt.

**Comment by kindohm** [comment]
I agree that the safety limits should be built into the synth, and not built into Tidal. If the limits were configurable in SuperDirt, that would be great!

**Comment by dktr0** [comment]
Whether the parameter limits are in Tidal or in the synth either way you need two pathways accessible at the live coding level so that when people know that they need extra gain, in that moment, on that "track", they can access it easily. Just putting limits in SuperDirt does not cover this.

**Comment by yaxu** [comment]
@dktr0 So extra `rawGain`, `rawShape` etc params?

**Comment by kindohm** [comment]
Maybe I'm misunderstanding something.

I agree with @dktr0 that the user needs to be able to change parameters like `gain` so that they can change the level of something on the fly.

I do not think that Tidal should prevent a user from typing a value like `# gain 4` when the user _knows_ that they have a very quiet sample and needs it to be louder. This is currently a problem for me as I have some quiet sounds which refuse to get louder beyond `# gain 1.3`, it seems. I've always perceived this as an issue with SuperDirt and that I should file an issue there. 

My point is that I do not think the Tidal user should be limited to someone else's idea of a safe value for `gain`. If I have a very, very quiet sample, then `# gain 5` is reasonable code to me and Tidal should let me do that. On the other hand, if my sample peaks at 0db and I do `# gain 10`, then I would expect SuperDirt to be more sensible than Tidal about how to protect my ears. Tidal knows nothing about my samples, but SuperDirt does.

Other params like `shape` are a different story. I'm mainly just addressing `gain` here.

**Comment by dktr0** [comment]
@yaxu yes
@kindohm many Tidal users, and especially many potential new Tidal users, need safety far more than they need extra gain. having different parameter channels for unrestricted vs. restricted gain addresses the needs of both users like yourself and users not like yourself.

**Comment by telephon** [comment]
By default, there is a limiter in superdirt, so I am not sure what else to do. I find a limiter alrady quite intrusive (while reasonable in general), because it induces latency in the signal.

**Comment by dktr0** [comment]
@telephon to support this in SC you would give the synths two gain arguments, one which is restricted to support the safety of young and/or sensitive ears and bodies:
``
arg gain=0.1,extraGain=1.0;
var effectiveGain = gain.clip(0,12.dbamp) * extraGain; // safe gain limited to +12 db
``
No latency.

**Comment by dktr0** [comment]
Again, this is a super standard element of audio safety - no one makes mixers or DAWs with faders that go up to +inf db...

**Comment by dktr0** [comment]
(...and there is absolutely no way in which this safety comes at the cost of literally anything that expert users might want to do...)

**Comment by kindohm** [comment]
> @kindohm many Tidal users, and especially many potential new Tidal users, need safety far more than they need extra gain. having different parameter channels for unrestricted vs. restricted gain addresses the needs of both users like yourself and users not like yourself.

Sure, makes sense. If a user can easily remove the restrictions, when desired, then I'd be OK with that.

**Comment by telephon** [comment]
why not `signal.clip2(maxGain)` ?

**Comment by dktr0** [comment]
That would be limiting the audio signal, while we need to protect against mistakes with the gain levels of individual tracks. Limiting does not provide such protection, unless it is done so aggressively as to produce a system without any dynamic range.

**Comment by telephon** [comment]
the limiter only delays the signal, but shouldn't touch it as long as it is below the limit.

```
(
{
	var amp = Line.ar(0, 1, 0.03);
	var bad = Line.ar(0, 1e4, 0.01);
	var sig = amp * SinOsc.ar(80);
	[amp, Limiter.ar(amp), Limiter.ar(sig * 10), Limiter.ar(bad)]
}.plot(0.1, separately: true)
)
```

and the last element also shows that it does provide such a protection.
Maybe I misunderstood you. I'm not sure what you mean by tracks.

**Comment by dktr0** [comment]
It only provides "protection" at the expense of dynamic range. Typically the more high fidelity the system is and/or the more people/tracks you have sharing it, the less acceptable such an already questionable compromise becomes. 

You don't have to take my word for it: try to get 8 workshop participants (or 8 imaginary people in the form of independent Tidal layers all trying to be heard) to share the current Tidal-SuperDirt status quo and you'll notice right away that it sounds terrible because of the limiting. You'll have problems, for example, where the sounds of one person are making the limiting kick in and reducing the gain on other unrelated sounds. So say you then attempt to solve that problem by making the limiting less aggressive (expanding dynamic range) - now you are making the system progressively less safe for people. This is an unnecessary trade-off...

In a system with appropriate dynamic range and protection against unsafe gain settings (in the form of limiting of those gain settings themselves, which again doesn't preclude an unrestricted pathway being there for people that "know what they are getting into") when someone accidentally makes a high gain setting they didn't intend what they get instead is a lower gain setting (still somewhat high) that is more or less within the normal dynamic range of the system, and so the sound is still basically clean, just a bit too loud. A gentle, graceful and much safer handling of an inevitable and recurrent problem.

By contrast in a setting where limiters (normally used to maximize loudness, manage dynamic range) are being misused as "safety", when someone accidentally makes a high gain setting they didn't intend, what they get instead is that they hit the limiter/clipper hard, still get a very loud sound, and possibly a nasty surprise and further physical damage to their ears in the form of additional mid-high and high frequency components introduced by the limiting/clipping itself.

Again, all I am asking for here is the same level of safety that would be provided by any standard mixer or DAW, and it costs nothing in terms of restricting what anyone can do.

**Comment by telephon** [comment]
I'm completely open to anything. I'm not using limiters at all myself, I prefer `tanh`.

This is why I left the options open, so you can just roll your own:

```supercollider
SynthDef("dirt_monitor" ++ numChannels, { |dryBus, effectBus, outBus, gate = 1|
		var drySignal = In.ar(dryBus, numChannels);
		var wetSignal = In.ar(effectBus, numChannels);
		//var signal = XFade2.ar(wetSignal, drySignal, dry * 2 - 1);
		var signal = wetSignal + drySignal;
		var post = if(SuperDirt.postBadValues) { 2 } { 0 };

		signal = Select.ar(CheckBadValues.ar(signal, post: post) > 0, [signal, DC.ar(0)]);

		signal = Limiter.ar(signal);

		// or if you like it harsher
		//signal = tanh(signal);
		// or:
		//signal = distort(signal);

		DirtPause.ar(signal, graceTime:4);

		signal = signal * EnvGen.kr(Env.asr, gate, doneAction:2);
		Out.ar(outBus, signal)
	}, [\ir, \ir, \kr, \kr]).add;
```

even on the fly.

Someone wanted a limiter, so I left that one in there.

But yes, if there is agreement that it should be different, please make a pull request, I'd be glad!

**Comment by telephon** [comment]
One more thing: the limiting is per orbit, so a "quick fix" is to give everyone a different one.

**Comment by yaxu** [comment]
I think it's pretty standard for even pro audio equipment to have a limiter of some kind. I don't think we should get rid of it, by default. It would be good to have more documentation about it on the wiki, though. I'll have to try some blind A-B testing of the options myself..

The default BootTidal.hs gives each 'd' alias a separate orbit, up to d12.

**Comment by dktr0** [comment]
Definitely not suggesting not having audio limiters. However, they emphatically do not solve the problem I am concerned about. If they did, I would not be raising the concern! Having used Tidal in many hundreds of group settings with thousands of people over the past few years, I know that this is necessary and that limiters don't cut it.

In these circumstances, I submitted a pull request that *adds* a safe version of gain with a different name. It doesn't break or change anything for anyone. It preserves existing behaviour 100% (as in - literally nothing changed about gain, SuperDirt, whatever). It 100% solves the problem I was concerned about, as someone often in the situation of working with Tidal in larger groups, and larger groups of beginners in particular. It doesn't even require any work from anyone (unless we change the name slightly) - it's already ready to go. Why not just accept this into the ecosystem (change the name if you like, so long as it something simple and meaningful) and let users use it if they will? What is the actual problem with having a safe version of gain in Tidal?

**Comment by yaxu** [comment]
I don't think anyone is arguing against limiting control values. We're discussing implementation in a way that covers all risky params.

**Comment by yaxu** [comment]
Thinking on this I like the term 'overdrive' for pushing tube amps.
So with sensible limits applied we could have `overgain`, `overlpf`, `overshape` etc. (probably with aliases `overGain` and so on) for going beyond them.
As per GPL no warranty implied etc in either case!

I think the default limits on `gain` etc should be set in superdirt and friends rather than in Tidal, because
* limits might well be implementation specific, or on some filters maybe even dependent on current samplerate
* more generally, fundamentally, Tidal is just a way to pattern OSC over time, it's nice to be able to use a parameter to send to some device without having to check if there's an enforced range.

**Comment by yaxu** [comment]
I wonder whether in an ideal world `gain` should have a default of `0.5` and a maximum of `1`. That would be a horrible UI change for a lot of people at this point though. So maybe leave `gain` as-is with a range of 0-2, but maybe add `vol` that scales it by half

**Comment by yaxu** [comment]
Or maybe it should be `-1` silent, `0` for 'normal' and `1` for 'double' loudness.
 
Pan is 0-1 but I think that would actually be better as -1 to 1, where `0` is the first speaker, `1` is the last one, `0.5` is halfway between, and the same negative numbers but in reverse.

**Comment by dktr0** [comment]
The 'over' convention makes sense.

One *could* limit parameter ranges in both places, sender and receiver, in line with the conventional networking maxim of "being liberal in what you receive, but conservative in what you send", ie. expect that input might be dangerously out of range, try to ensure that output isn't. I realize such extra safety may be a hard sell with the present audience, so am definitely not pushing the idea, however, consider that such measures could evolve into Tidal issuing a warning when pattern parameters are possibly out of the defined range (by Patterns including logic around minima and maxima that propagate when Patterns are combined; when I parse "0 0.5 10" it is easy to register that the min and max are 0 and 10 and for this to translate into  warning that also propagates upwards when combined with 'gain').

While we are thinking about gain, it would be nice to be able to specify it in (negative, mostly) dB, as per SuperCollider and DAW custom. If gain involved a predictable translation into db, then an alias db could be built over gain with the same translation in reverse. One such translation could be:
0 => -inf dB
(0,1] => (-120,0] dB  
(1,2] => (0,12] dB
This is kind of the mapping of a DAW fader.

**Comment by yaxu** [comment]
db sounds good - if you can tell me what the maths should be I'd be happy to add that to parseBP, so `# gain "6db` would end up with something between `1` and `2` being sent

**Comment by yaxu** [comment]
Re warnings - values only come out of patterns in the scheduler, which would be a bit late, really.. Unless we got the parser to add all the parsed values to the new pattern 'context' field.

**Comment by bgold-cosmos** [comment]
amp is gain^4 so if `# gain 1` is 0 dB then I believe the conversion is `log(gain**8)/log(10) * 10` for gain -> dB or `10**(dB/80)` for dB -> gain

**Comment by yaxu** [comment]
Doesn't seem to be completely right:
```
Prelude> let db g = log(g**8)/log(10) * 10
Prelude> db 0
-Infinity
Prelude> db 0.5
-24.082399653118493
Prelude> db 1
0.0
Prelude> db 1.5
14.087300724454499
Prelude> db 2
24.082399653118493
```

**Comment by yaxu** [comment]
oops that's the wrong way round sorry!

**Comment by yaxu** [comment]
Another go:
```
Prelude> let db x = 10**(x/80)
Prelude> db 12
1.4125375446227544
Prelude> db (-120)
3.162277660168379e-2
Prelude> db (-50)
0.23713737056616552
Prelude> db 0
1.0
Prelude> db 1
1.0292005271944282
Prelude> db 24
1.9952623149688795
```

**Comment by yaxu** [comment]
@telephon could you limit gain to 0.. 2 and shape to 0..1 in superdirt please, adding overgain and overshape to multiply them? Then it would be easy to limit other parameters, following your example.

**Comment by yaxu** [comment]
@dktr0 if you can do the same with webdirt, I can have a look at classic dirt.

**Comment by yaxu** [comment]
Have implemented something for https://github.com/musikinformatik/SuperDirt/issues/166

I decided additive was best, i.e. `gain.min(2) + overgain` and `shape.min(1) + overshape`. I didn't think e.g. `gain 2 + overgain 0` should equal zero via multiplication.

Testing this, the current dsp limiter still feels pretty safe to me. I'm just testing with laptop speakers, but looking at the scope. It could just be a matter of not being on a large PA, but I'm wondering if there are platform implementation differences, or different behaviour if sc3plugins isn't installed.

**Comment by yaxu** [comment]
In particular if I do `d1 $ sound "bd" # overgain 4`, the onset isn't any louder than with `# overgain 2`, you can just hear the tail of the sound just as loud as the onset.
