### ISSUE TITLE
time cost of randomness in Tidal

### ISSUE THREAD

**Issue by dktr0** [tidalcycles/Tidal#636]
Some evidence/experience with Estuary suggests that Tidal functionality to do with randomness is relatively expensive in terms of time cost. For example, the following contrived example brings Estuary performance crashing down (by comparison, it is typically no problem to have many layers of complex patterns working without problem without randomness in Estuary):

`sometimes (# speed 0.5) $  sometimes (# speed 0.5) $  sometimes (# speed 0.5) $  sometimes (# speed 0.5) $  sometimes (# speed 0.5) $  sometimes (# speed 0.5) $  sometimes (# speed 0.5) $  sometimes (# speed 0.5) $  s "jazz*16" # n (run 16) `

Last time I looked at this (and I think motivated a switch to a somewhat cheaper randomness library) I think the approach is still to reseed the randomness library from the elapsed cycles at every request for a random value. I understand how the determinacy of this is desirable (to some, and easily circumventable by those to whom it is not desirable). What I am wondering however is if the computational cost of that seeding operation might be high, and if we could cut or eliminate that cost by calculating the pseudo-random value directly from the time instead of via the intermediary of the seeding operation? Since it is just a function of time anyway...

**Comment by jwaldmann** [comment]
There's something strange going on in your example, but are you sure it's the cost of rand? I made this test case: https://github.com/jwaldmann/tidal-fuzz-test/blob/master/Rand.hs . If we just do
```
foldr ($) (run 16)  $ replicate i  $ sometimes (const 0)
``` 
then it's fine. If we do
```
foldr ($) (speed (run 16))  $ replicate i  $ sometimes (# speed 0)
``` 
(that's your example) then part of the output appears immediately:
```
[](0> 1/16)|speed: 0.0f
...
[]( 13/16>⅞)|speed: 13.0f
```
and here it stops for a while, before finally printing
```
[]( 3/16>¼)|speed: 0.0f
...
[]( 15/16>1)|speed: 0.0f
```
when stacking more operations, the wait gets progressively longer. - In my repo, do
```
stack test :tidal-rand-test
```
to build and run, then
```
stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build/tidal-rand-test/tidal-rand-test 20
```
to execute while setting an argument.

**Comment by dktr0** [comment]
It's definitely got something to do with rand or is much exacerbated by rand:

`foldr ($) (speed (run 16)) $ replicate 12  $ sometimes (# speed 0)`

The code above evaluated in GHCI with the latest version of Tidal on my "nothing special" laptop has a noticeable lag before returning, but this (without randomness, same number of iterations) returns immediately:

`foldr ($) (speed (run 16)) $ replicate 12  $ (# speed 0)`

**Comment by dktr0** [comment]
(PS - I wonder if the difference in performance between your two examples had to do rather with the fact that only the second is Pattern ControlMap, and it is the strict version of Map that is being used?)

**Comment by jwaldmann** [comment]
ControlMap or not  - I have no idea.

Can you confirm that part of the output appears immediately?

I am building my test case with profiling, to see what functions are active.

**Comment by dktr0** [comment]
No I don't get the part of the output immediately in any of the "slow" examples we're posting here. But I think that could be machine/OS specific...

**Comment by jwaldmann** [comment]
Note the events that I see immediately have values > 0, while the events that are expensive to compute, have values = 0 (set by `# speed 0').

Profiling info:
```
COST CENTRE                MODULE                        SRC                                                %time %alloc

timeToSeed                 Sound.Tidal.UI                src/Sound/Tidal/UI.hs:(33,1)-(37,52)                43.2    2.0
basicUnsafeIndexM          Data.Vector                   Data/Vector.hs:290:3-62                             12.1    0.0
basicUnsafeIndexM          Data.Vector.Primitive         Data/Vector/Primitive.hs:234:3-75                    9.1   16.9
primitive                  Control.Monad.Primitive       Control/Monad/Primitive.hs:205:3-16                  8.7    0.7
basicUnsafeWrite           Data.Vector.Primitive.Mutable Data/Vector/Primitive/Mutable.hs:124:3-69            5.2   43.5
basicUnsafeIndexM          Data.Vector.Unboxed.Base      Data/Vector/Unboxed/Base.hs:291:841-899              5.1    0.0
basicUnsafeWrite           Data.Vector.Unboxed.Base      Data/Vector/Unboxed/Base.hs:290:1510-1571            1.8    0.0
sam                        Sound.Tidal.Pattern           src/Sound/Tidal/Pattern.hs:28:1-43                   1.3    3.9
sect                       Sound.Tidal.Pattern           src/Sound/Tidal/Pattern.hs:70:1-54                   1.1    0.7
cyclesInArc                Sound.Tidal.Pattern           src/Sound/Tidal/Pattern.hs:(108,1)-(111,40)          0.9    2.3
uniform                    System.Random.MWC             System/Random/MWC.hs:222:5-45                        0.6    1.1
```
so, yes, `timeToSeed` is at the top.

**Comment by dktr0** [comment]
Doing a little more testing in Estuary now I notice that there aren't problems when making many independent layers (with stack) that each have one random expression in them. And there are problems quickly if multiple random expressions go into the same ControlPattern. This makes me (perhaps all too quickly) hypothesize that the merge # operator is O(N2) or worse, and when this combined with a somewhat more expensive input like rand this becomes more palpable... just thinking out loud...

**Comment by dktr0** [comment]
And I think all those Vector operations are part of the rand infrastructure too - if so they are responsible for ~3/4 of the time cost!

**Comment by jwaldmann** [comment]
not quadratic, but much worse:
```
for n in 4 5 6 7 8 9 10 11 12 13 ; do echo -n $n " : " ; /usr/bin/time -f '%e' .stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build/tidal-rand-test/tidal-rand-test $n >/dev/null ; done
4  : 0.03
5  : 0.06
6  : 0.13
7  : 0.26
8  : 0.56
9  : 1.04
10  : 2.08
11  : 4.21
12  : 8.67
13  : 16.82
```

**Comment by dktr0** [comment]
Which I think brings me back to my original question, could we make random values a simple function of time? (along the lines of a linear congruential generator, with the previous value always simply the time) https://en.wikipedia.org/wiki/Linear_congruential_generator

And if the common merge operator is worse than quadratic, why and could that be improved?

**Comment by jwaldmann** [comment]
I'd like to first  understand what's happening here. It is some interplay between `sometimes(By)` and `#` with exponential badness. Replacing the random gen would not help much, then, as it just changes a constant factor.

**Comment by dktr0** [comment]
Yeah, and I just did another test piling up lots of degradeBy-s and there was no problem. Am looking more closely at sometimesBy now.

**Comment by jwaldmann** [comment]
Oh, you're saying that both `degrade` and `sometimes` use `rand` so we could hope that both can be fast?

I should adapt https://github.com/jwaldmann/pretty-test to find more examples of tidal combinators that are expensive when stacked.

**Comment by dktr0** [comment]
Right - degrade seems to be okay even stacked - `sometimes` seems to be not okay when stacked

**Comment by dktr0** [comment]
Here's an example that's already surprisingly slow in the resource-challenged environment of Estuary:
`sometimes (# s "tink") $ sometimes (# s "tink") $ sometimes (# s "tink") $ sometimes (# s "tink") $ sometimes (# s "tink") $ sometimes (# s "tink") $ sometimes (# s "tink") $ sometimes (# s "tink") $ s "tink"`

**Comment by dktr0** [comment]
I think I've gotten as far as understanding how chaining "sometimesBy" (etc) is O(N squared) or worse. It's defined as this:

`sometimesBy :: Pattern Double -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a
sometimesBy x f p = overlay (degradeBy x p) (unDegradeBy x $ f p)`

If you have one of these, then you have 2 rand calls. If you have two of them, you have 4 rand calls. If you have three of them, you have 8 rand calls. By the time you have 8 as in the example immediately preceding, you have 64 rand calls and are very exposed to the cost of that operation whatever it may be...

I started making a variant of sometimesBy with only one rand call, but my initial attempts just made things worse. Will keep puzzling at it...

**Comment by kindohm** [comment]
more anecdotal, but I use _a lot_ of randomness in my very large stacks of patterns and have noticed very long waits between when I eval code and when I get output from the ghci REPL. I use a lot of `sometimesBy` and a lot of `someCyclesBy`, maybe one or two of each in a pattern, with 4-8 patterns in a stack. I thought it was something with my IDE (VS Code) but perhaps this performance issue with randomness is what I'm observing.

**Comment by jwaldmann** [comment]
NB: above I wrote that some output appears immediately, and some, only later. This happened because I was using a Tidal version where the `show` implementation for `Pattern a` did _not_ sort events by time. 

That's been changed meanwhile (`sortOn` in https://github.com/tidalcycles/Tidal/commit/c4eb09131f21d4254606335d387b62082c8ab6cc#diff-450d7488fef6c795f177dfdad909dcd1R18) and now all output is late.

**Comment by jwaldmann** [comment]
Are we running into some form of the "observable sharing" problem here? The implementation uses the name `p` two times.
```
sometimesBy x f p = overlay (degradeBy x p) (unDegradeBy x $ f p)
```
We would hope that `p :: Pattern a` is still evaluated just once, which is true technically, but not in the sense that all events of the pattern would have been  computed explicitly. Recall that a Pattern is really a function
```
data Pattern a = Pattern {query :: Query a}
type Query a = State -> [Event a]
data State = State {arc :: Arc, controls :: StateMap}
```
so the value of argument `p` above is a function, and each time we we use it, it will be evaluated (applied to `arc` and `controls`). At this point, the runtime system cannot detect repeated evaluation of identical sub-expression (a sub-pattern queried for some arc). Effectively, this removes all (operational) sharing that seems to be present notationally (in the source code).

By that reasoning, any function that duplicates an argument of type `Pattern a`, risks running into the behaviour that was observed for `sometimes`. Is that so?

It was mentioned above that `degrade` is fine (when stacked), and indeed, the implementation is linear in `p`:
```
_degradeByUsing prand x p = fmap fst $ filterValues ((> x) . snd) $ (,) <$> p <* prand
```
The work-around is to "reify" patterns (from function to collection of events)
but that would need to know all query arguments (arcs) in advance.

The work-around to this is to compute as-needed, but store argument (arc) and result, in a cache (local to the pattern). That's hard to do in a pure language, because that contents of the cache changes as a side effect of evalution. Of course that's benign, but the compiler won't believe you. 

So either you make that state explicit. That's a heavy change: everyone gets an extra "cache" argument and result. You could hide that behind a state monad but the this would change all function application  `f x y` to applicative `f <$> x <*> y`.

Or you hide the cacheing  behind `unsafePerformIO`, as in this example, where an AST of a propositional logic formula is translated to a circuit description https://github.com/ekmett/ersatz/blob/master/src/Ersatz/Bit.hs#L134 

In Tidal, as `arc` isn't the only argument of a query - we also have `controls`. Should they also be keys for the cache?

**Comment by yaxu** [comment]
I'd be interested in how this benchmarks compares to `sometimesBy`:
```haskell
_sometimesBy  :: Double -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a
_sometimesBy x f p = overlay (_degradeBy x p) (_unDegradeBy x $ f p)
```
I.e., whether the patterned first parameter makes a difference.

Tidal does have a benchmarking suite that runs with every jenkins build, it'd be good to start capturing costly things in there, so we can compare different versions of tidal, including looking at older versions to see if they were faster.

Surprisingly for FRP, I've rarely had cause to look at efficiency with Tidal, but feel that cpu usage probably has crept up.. So it would be great to look at that.

@dktr0 coming back to your original proposal, randomness has to come from cycle time within a pattern, and not an external clock or external state.. Otherwise when you try to reverse or shift a 'random' pattern, nothing will happen.

**Comment by yaxu** [comment]
Related: https://github.com/tidalcycles/Tidal/issues/564
I've seen that `fix` is not really usable more than a couple of times in one pattern.

My guess is that Tidal could be made a lot more efficient, just based on the fact that it's never really been optimised. However that doesn't mean that there's necessarily 'low hanging fruit', because it's so declarative it's hard to imagine what's really going on..

**Comment by jwaldmann** [comment]
@yaxu  Re: `sometimesBy` vs. `_sometimesBy` : 

like this? https://github.com/jwaldmann/tidal-fuzz-test/blob/master/Rand.hs#L20 
It does not seem to make a difference.

**Comment by dktr0** [comment]
@yaxu "Or maybe I'm misunderstanding you and you're just suggesting we find a cheaper way of arbitrarily mapping from cycle time to a number, in which case, agreed." - Yes that is what I was suggesting. I believe timeToRand is inefficient because it wastes a bunch of time allocating vectors that are then only used once.

**Comment by dktr0** [comment]
I also did some anecdotal experiments with the patterned Time parameters and didn't notice any performance hit there. I also made an alternate implementation of sometimesBy that made things worse - and the reason it made things worse was because it used <*> which seems to be particularly expensive.

**Comment by jwaldmann** [comment]
I believe it's not about `rand` at all. See #564 (linked above) for expensive stacking of `fix`. That issue mentions `sometimes` in the title but I think that is not essential (my test case does not use it).

**Comment by dktr0** [comment]
Well replacing timeToRand with this little thing I just cooked up based on the C++11 mindstd_rand0 algorithm definitely makes things faster... Haven't had time yet to check how good the results are:

`timeToRand :: Real a => a -> Double
timeToRand t =
  let t' = toRational t * 48271
      t'' = numerator t' + denominator t'
  in realToFrac (lcg t'') / 2147483647`

**Comment by dktr0** [comment]
PS - also eliminates a library dependency!...

**Comment by jwaldmann** [comment]
if you're going down that road ... avoid `toRational`, because it does strange (and possibly expensive) things, e.g.
```
toRational  0.9
8106479329266893 % 9007199254740992
```
Where does the `Real` constraint come from?

**Comment by dktr0** [comment]
It looks like there are a few places that are using timeToRand with a type other than Rational -> Double. I don't know the details. In the main case though the a in a -> Double is in fact Rational so toRational is basically a no op.

**Comment by yaxu** [comment]
Do you have that to hand for a PR @dktr0 ?

I'd call this a breaking change, for those relying on particular random streams, so I might look around for other quick breaking changes that could go into a 1.5 release.

**Comment by dktr0** [comment]
Sure will push it now.

**Comment by kindohm** [comment]
Will it be possible to use a the original behavior of randomness after the change is pushed? Something like `sometimesByOld`?

Tidal's current behavior with random streams has been very fun to exploit in compositions and live coding.  

Although not ideal, users could always install an older version of Tidal if they really want the old behavior.

**Comment by bgold-cosmos** [comment]
@kindohm If I understand correctly I don't think it should break the behavior that "same time -> same random number".  The time->random mapping will just be _different_ than it was before the change.  So if you were relying on `timeToRand 0` being 0.5000843864305976, yes, your code will break, but otherwise I think you're OK.

**Comment by yaxu** [comment]
Yes, this 'breaking change' is just for people who have built compositions that rely on random numbers at start from cycle 0. Otherwise it should be the same.

**Comment by kindohm** [comment]
got it, thank you @bgold-cosmos & @yaxu!

**Comment by dktr0** [comment]
think I have an even faster and better one - just testing before committing...

**Comment by dktr0** [comment]
Here's the pull request https://github.com/tidalcycles/Tidal/pull/640

I've also contributed this work to the tempi library so it is available for other projects/languages.

Anecdotally speed up seems to be a modest 25% in Estuary, but likely more in ghci (where there is a strong possibility the bitwise operations get compiled down to machine-efficient code).

Anyway, refactoring sometimesBy to not have the O(N squared) characteristic would be a separate and worthwhile project that would still make a further difference.

**Comment by yaxu** [comment]
Thanks @dktr0

**Comment by yaxu** [comment]
I don't propose that we reverse this change, but out of interest, version 1.2.0 of the random library is now potentially 1000x faster https://github.com/haskell/random/blob/master/CHANGELOG.md

We do still use it for some things in Sound.Tidal.Stream, so worth a note..

**Comment by yaxu** [comment]
Yes agreed, just flagging out of interest, really.
