### ISSUE TITLE
Haskell Language Server plugin

### ISSUE THREAD

**Issue by tonyday567** [tidalcycles/Tidal#767]
Has anyone looked at the mechanics of making Tidal a haskell-language-server plugin?

It would then work the same across all IDE platforms, and piggyback off of their shortcuts and protocols.

**Comment by yaxu** [comment]
Hi @tonyday567, no not in detail.. Certainly would be very excited about the possibility though, especially as I believe they've made distributing a haskell interpreter a function of the editor plugin, which would also make tidal much easier to install!

**Comment by yaxu** [comment]
I guess the question is whether the assumptions of HLS - which I imagine come from a 'traditional' approach to software development, fit with tidal's, which are more about REPL-like conversational programming.

**Comment by yaxu** [comment]
Are you having a look at this @tonyday567 or was it a friendly suggestion for others to take up?

**Comment by yaxu** [comment]
That's a shame. I wonder if still we could gain from their approach. Being able to distribute tidal as a binary api would be such a huge win, especially if an editor plugin could download and run it automatically.

**Comment by jwaldmann** [comment]
Not easy - we still need a working GHC installation ("BootTidal.hs as an executable" would need to create a GHC session, that needs to find libraries when started, ...)

**Comment by yaxu** [comment]
That's right @jwaldmann, not easy, but I think possible without requiring a whole ghc installation.

Using the `hint` library, you can make a binary. You can then create a package database with the libraries it needs, with some hacking to make it relocatable. Under linux you would also need some libraries like libgmp, libpthread etc packaged up with it, or maybe a static build is possible? The hint library calls gcc, but only to print out the file names of libraries, so you can replace that with a simple shell script that simply echoes back one of its arguments.

I tried to get this working and made some progress but with a relocatable build, but I don't think I actually got it working to the point that it could be copied to a fresh linux install and run: https://github.com/tidalcycles/tidali

This was based on the work here: https://github.com/gelisam/deploy-hint/tree/85918a527c8801f5b56f94897e6744c2cc86ee38

Which arose from the discussion here: https://github.com/haskell-hint/hint/issues/3

In the end I stopped working on this because while a relocatable binary distribution for linux would be nice, the real benefit would be for windows or mac where that's the standard way to install things. It seems the same approach would work there but I don't use windows or mac os myself. 

For linux it would perhaps be more natural to make a .deb, which is already done for lots of distros via stackage.

@tonyday567 There is a "build a tidal binary" ticket here -> #315
and also a 'tidal api' ticket here -> https://github.com/tidalcycles/Tidal/issues/682 with ongoing work here -> https://github.com/tidalcycles/tidal-listener

A whole other and more recent approach by @cleary is via ansible playbooks, which is working very well under linux: https://github.com/cleary/ansible-tidalcycles

**Comment by cleary** [comment]
I was doing a preliminary investigation into supporting arch Linux for my ansible installer, and t1mpuk showed me the Haskell-tidal package that exists in arch:
https://archlinux.org/packages/community/x86_64/haskell-tidal/

It still requires a manual superdirt install, but has it potentially solved some of the issues already?

**Comment by yaxu** [comment]
Yes there is a package in debian too: https://packages.debian.org/sid/libghc-tidal-dev
The versions lag of course, especially in debian, but it's a useful basis for further work. I think the supercollider distro versions are usable these days too.

I think the tidal packages are via stackage https://www.stackage.org/package/tidal

**Comment by tonyday567** [comment]
This might be a good place to start: https://github.com/gelisam/deploy-hint

Get a working instance of a dynamically relocated *something*, and then see if you can pack tidal in there?

**Comment by yaxu** [comment]
@tonyday567 yes tidali is based on that deploy-hint example. I'm not at all familiar with docker so am finding it tough to get a good workflow going.
