### ISSUE TITLE
chord not working with inversion (eg 'ii) and number of notes contained (eg '6) together 

### ISSUE THREAD

**Issue by cleary** [tidalcycles/Tidal#777]
**Describe the bug**
A chord can be described with an inversion (change the starting note in the chord)

```
-- eg second inversion
note (arp "converge" "c'maj7'ii")
```

and it can be described to contain a certain number of notes (ascending)

```
-- eg six notes in the chord
note (arp "converge" "c'maj7'6")
```

It's previously been possible to combine both of these arguments:

```
-- eg six notes in the chord, second inversion
note (arp "converge" "c'maj7'ii'6")
```

but this is throwing an error on the latest 1.7 tidal:

```
tidal> Warning: GHCi | Error in pattern: Syntax error in sequence:
Warning: GHCi |   "c'maj7'ii'6"
Warning: GHCi |             ^  
Warning: GHCi | unexpected '\''
Warning: GHCi | expecting float, rest, "[", "{", "<", "^", ".", "?" or end of input
```

**Comment by Git-Christopher** [comment]
in using a slightly older version of tidal (1.6.1), i can confirm that i do not get an error. however (!) i am not getting the expected behavior when using the inversion and step arguments in tandem.

`--in the example below, i hear 8 steps before the figure repeats (not 6)
note (arp "converge" "c'maj7'ii'6")`

what's interesting is that if i increase the steps from 6 to 16, the code does not evaluate to produce 16 total steps; it gives one long note for the first half of the cycle and then plays the last four notes from the above example.

`note (arp "converge" "c'maj7'ii'16"
--only plays 5 notes total`

even more curious is when i enclose the pattern in angled brackets, it plays the phrase at half speed

`note (arp "converge" "<c'maj7'ii'16>")
--is the same as
slow 2 $ note (arp "converge" "c'maj7'ii'16")`

**Comment by cleary** [comment]
https://github.com/tidalcycles/Tidal/pull/931
