### ISSUE TITLE
Make Pattern instance Monoid/Semigroup

### ISSUE THREAD

**Issue by fbous** [tidalcycles/Tidal#864]
As [discussed in the forum](https://club.tidalcycles.org/t/how-to-use-the-operator-of-overlay/3559) the `<>` operator, defined in `Sound.Tidal.Core`, qualifies as `Semigroup`.  Implementing `Pattern a` as `Semigroup` would avoid ambiguity between `Prelude.<>` and `Sound.Tidal.Core.<>` without changing its behaviour while enabling the features provided by `Semigroup`/`Monoid`.

**Comment by yaxu** [comment]
Looks like this is breaking older ghc's, IIRC there were major semigroup changes pre ghc 8.4.

It turns out that there was a monoid and semigroup instance before. I can't remember exactly why I removed them, it says here that they were "freezing things":
  https://github.com/tidalcycles/Tidal/pull/291/commits/e7148a767e35be82275fbddbd6b94b9cbda3a982

Perhaps this was the old travis ci build freezing due to the semigroups issue.

Now debian stable is up to ghc 8.8.4 and oldstable is on 8.4.4 I guess we can drop support for the four year old ghc 8.2.2 and accept this change?

**Comment by yaxu** [comment]
Done!
