### ISSUE TITLE
preplace (and general prrw) signature/parsing issue

### ISSUE THREAD

**Issue by bgold-cosmos** [tidalcycles/Tidal#96]
As Lennart pointed out on Slack, I believe some other 0.7 changes broke `preplace`.  The issue is that the a typical usage is `d1 $ sound $ preplace (1,1) "x [~ x] x x" "bd sn"`.  But the parser can no longer figure out what type of Pattern "x [~ x] x x" is.  This might be related to magical autoparsing of note names into MIDI notenumbers, but maybe not, I'm not sure.

It works again if you say `d1 $ sound $ preplace (1,1) ("x [~ x] x x"::Pattern String) "bd sn"`, but it would be nice not to have to do this.  And for `preplace`, the type of Pattern there doesn't actually matter!  So one solution is to just force Pattern String in the type signature.  This runs into another problem, though, which is that `protate` (and the ~>>, <<~ operators) are implemented by replacing a pattern with itself, so forcing Pattern String breaks stuff like `n (2 ~>> "0 1 2 3")`.

I'm raising this as an issue because I'm at a loss how to fix this without breaking the generality of `prrw` or something else.  Maybe the solution lies in the parser, but that's voodoo to me and I don't understand it.

**Comment by yaxu** [comment]
The old type of 
`preplace :: (Time, Time) -> Pattern a -> Pattern a -> Pattern a`
had the problem that it would always parse the beat pattern using the same parser as the valuepattern.. I.e. if the value pattern was of type `Pattern Int` that would fill in the wildcard for all the `a`s giving `preplace :: (Time, Time) -> Pattern Int -> Pattern Int -> Pattern Int`

The new type of
`preplace :: (Time, Time) -> Pattern a -> Pattern b -> Pattern b`
has problems because unless you explicitly tell it, Haskell won't know what the `a` is from the context, so it won't be able to parse the pattern.

This should work fine:
`preplace :: (Time, Time) -> Pattern String -> Pattern b -> Pattern b`

**Comment by bgold-cosmos** [comment]
That fixes `preplace`, but you need to make a corresponding change to `prrw` (which makes it less general, but OK), and also breaks `protate` unless you also change it to only work on String Patterns, because `protate` is implemented by replacing a pattern with itself.  So `protate` would lose functionality.

To keep functionality it might be possible to reimplement things so there are two underlying functions, the general `prrw` which could be used where the type is explicit (like with `protate`), and another version that forces Pattern String to use with `preplace` where the type is otherwise ambiguous.  

That seems kinda clunky; I was hoping there might be a better way.  But I probably should just try to implement it and make sure it works.
